<?php
/**
 * @file
 * Install, update and uninstall functions for the guifi module.
 */

function guifi_uninstall() {

  drupal_uninstall_schema('guifi');

  variable_del('guifi_license');
  variable_del('guifi_title');
  variable_del('guifi_root');
  variable_del('guifi_forums');
  variable_del('guifi_contact');
  variable_del('hotspot_ssid');
  variable_del('guifi_loglevel');
  variable_del('guifi_maps');
  variable_del('guifi_decimal');
  variable_del('guifi_thousand');
}

function guifi_schema() {
  $schema['guifi_notify'] = array(
    'fields' => array(
         'id' => array('type' => 'int', 'size' => 'small', 'unsigned' => TRUE, 'not null' => TRUE),
         'timestamp' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
         'who_id' => array('type' => 'int', 'size' => 'medium', 'unsigned' => TRUE, 'not null' => TRUE),
         'who_name' => array('type' => 'varchar', 'length' => '255', 'not null' => TRUE),
         'to_array' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
         'subject' => array('type' => 'varchar', 'length' => '255', 'not null' => TRUE),
         'body' => array('type' => 'text', 'size' => 'big', 'not null' => TRUE)
         ),
    'primary key' => array('id'),
  );

  $schema['guifi_location'] = array(
    'fields' => array(
         'id' => array('type' => 'serial',  'size' => 'medium', 'not null' => TRUE),
         'nick' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => ''),
         'zone_id' => array('type' => 'int',  'size' => 'medium', 'not null' => FALSE, 'comment' => 'foreign key to guifi_zone(id)'),
         'zone_description' => array('type' => 'varchar', 'length' => '255', 'not null' => FALSE),
         'location_type' => array('type' => 'varchar', 'length' => '10', 'not null' => 'TRUE', 'default' => 'node'),
         'lat' => array('type' => 'numeric', 'precision' => '10', 'scale' => '6', 'not null' => FALSE),
         'lon' => array('type' => 'numeric', 'precision' => '10', 'scale' => '6', 'not null' => FALSE),
         'elevation' => array('type' => 'int', 'size' => 'tiny', 'not null' => FALSE),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
         'status_flag' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => 'Planned'),
         'project_id' => array('type' => 'int', 'size' => 'medium', 'not null' => 'FALSE'),
         'stable' => array('type' => 'varchar', 'length' => '25', 'not null' => TRUE, 'default' => 'Yes', 'comment' => 'Yes,No'),
         'graph_server' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => 0, 'comment' => 'FK to guifi_services (SNPGraphs)'),
         'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int', 'size' => 'medium',' not null' => FALSE),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => FALSE)),
    'primary key' => array('id'),
    'indexes' => array(
        'lat_index' => array('lat'),
        'lon_index' => array('lon'),
        'zcs_index' => array('zone_id', 'timestamp_created', 'status_flag'),
        'year_index' => array('timestamp_created'),
        'status_index' => array('status_flag'),
        'project_index' => array('project_id'),
    ),
  );

  $schema['guifi_networks'] = array(
    'comment' => 'allocates ipv4 address ranges to zones',
    'fields' => array(
         'id' => array('type' => 'serial', 'size' => 'small', 'unsigned' => TRUE, 'not null' => TRUE),
         'base' => array('type' => 'varchar', 'length' => '255', 'not null' => TRUE, 'default' => ''),
         'mask' => array('type' => 'varchar', 'length' => '255', 'not null' => TRUE, 'default' => '255.255.255.0'),
         'zone' => array('type' => 'int',  'size' => 'medium', 'unsigned' => TRUE, 'not null' => TRUE),
         'network_type' => array('type' => 'varchar', 'length' => '10', 'not null' => TRUE, 'default' => 'public', 'comment' => 'public, backbone'),
         'user_created' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('id'),
    'unique keys' => array(
         'networks' => array(array('base', 16), array('mask', 16))),
    'indexes' => array(
         'net_zone' => array('zone')),
  );

  $schema['guifi_zone'] = array(
    'comment' => 'zone information, zones have a self hierarchy and group node locations',
    'fields' => array(
         'id' => array('type' => 'serial',  'size' => 'medium', 'unsigned' => TRUE, 'not null' => TRUE),
         'title' => array('type' => 'varchar', 'length' => '255', 'not null' => TRUE, 'default' => ''),
         'nick' => array('type' => 'varchar', 'length' => '10', 'not null' => FALSE),
         'body' => array('type' => 'text', 'size' => 'big', 'not null' => TRUE),
         'master' => array('type' => 'int', 'size' => 'medium', 'unsigned' => TRUE, 'not null' => TRUE, 'comment' => 'references parent zone guifi_zone(id)'),
//      'zone_mode' => array('type' => 'varchar', 'length' => 25, 'not null' => TRUE, 'default' => 'infrastructure', 'comment' => 'infrastructure/ad-hoc'),
         'graph_server' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => '0', 'comment' => 'FK to guifi_services (SNPGraphs)'),
         'proxy_id' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => '0', 'comment' => 'FK to guifi_services (proxy)'),
         'voip_id' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => '0', 'comment' => 'FK to guifi_services (VoIP)'),
         'time_zone' => array('type' => 'varchar', 'length' => '15', 'not null' => TRUE),
         'dns_servers' => array('type' => 'varchar', 'length' => '255', 'not null' => FALSE),
         'ntp_servers' => array('type' => 'varchar', 'length' => '255', 'not null' => FALSE),
         'graph_server' => array('type' => 'varchar', 'length' => '40', 'not null' => FALSE),
         'homepage' => array('type' => 'varchar', 'length' => '255', 'not null' => FALSE),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
         'ospf_zone' => array('type' => 'varchar', 'length' => '255', 'not null' => FALSE),
         'minx' => array('type' => 'numeric', 'precision' => '10', 'scale' => '6', 'not null' => FALSE),
         'miny' => array('type' => 'numeric', 'precision' => '10', 'scale' => '6', 'not null' => FALSE),
         'maxx' => array('type' => 'numeric', 'precision' => '10', 'scale' => '6', 'not null' => FALSE),
         'maxy' => array('type' => 'numeric', 'precision' => '10', 'scale' => '6', 'not null' => FALSE),
         'local' => array('comment' => 'Yes, No', 'type' => 'varchar', 'length' => '5', 'not null' => TRUE, 'default' => 'Yes'),
         'nodexchange_url' => array('type' => 'varchar', 'length' => '255', 'not null' => FALSE),
         'refresh' => array('type' => 'int', 'not null' => FALSE),
         'remote_server_id' => array('type' => 'int',  'size' => 'medium', 'not null' => FALSE),
         'host_nodes' => array('type' => 'int','size' => 'small', 'not null' => FALSE,'default'=>0,'comment'=>'The zone can host nodes? (TRUE=1, FALSE=0)'),
         'weight' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 0),
         'user_created' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('id'),
    'indexes' => array(
         'name' => array(array('title', 10)),
         'master_index' => array('master'),
    ),
  );

  $schema['guifi_devices'] = array(
    'fields' => array(
         'id' => array('type' => 'serial', 'size' => 'medium', 'not null' => TRUE),
         'nid' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'comment' => 'foreign key to guifi_location(id)'),
         'nick' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE),
         'type' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
         'mac' => array('type' => 'varchar', 'length' => '20', 'not null' => TRUE, 'default' => '00:00:00:00:00:00'),
         'mainipv4' => array('type' => 'varchar', 'length' => '20'),
         'comment' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE),
         'flag' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => 'Planned'),
         'extra' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE, 'comment' => 'store variable data depending on guifi_devices(type)'),
         'usc_id' => array('type' => 'int', 'not null' => TRUE, 'comment' => 'UnSolClic template id'),
         'mid' => array('type' => 'int', 'not null' => TRUE, 'comment' => 'Model Id'),
         'fid' => array('type' => 'int', 'not null' => TRUE, '' => 'Firmware Id'),
         'graph_server' => array('type' => 'int',  'size' => 'medium' , 'not null' => TRUE, 'default' => 0, 'comment' => 'FK to guifi_services (SNPGraphs)'),
	 'logserver' => array('type' => 'varchar','length' => '60', 'not null' => TRUE, 'comment' => 'Ip Server Logs'),
	 'last_online' => array('type' => 'int', 'not null' => TRUE, 'default' => 0, 'comment' => 'Last time that this device has been seen online'),
         'last_flag' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => 'N/A', 'comment' => 'N/A, Online, Offline...'),
         'ly_availability' => array('type' => 'numeric', 'precision' => '11', 'scale' => '2', 'not null' => FALSE, 'default' => NULL),
         'last_stats' => array('type' => 'int', 'not null' => TRUE, 'default' => 0, 'comment' => 'Last time that this device has been loaded with statistics'),
         'latency_avg' => array('type' => 'int',  'size' => 'small', 'not null' => TRUE, 'default' => 0, 'comment' => 'Average latency'),
         'latency_max' => array('type' => 'int',  'size' => 'small', 'not null' => TRUE, 'default' => 0, 'comment' => 'Maximum latency'),
         'user_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('id'),
    'unique keys' => array(
         'nick' => array('nick')),
    'indexes' => array(
        'nid_index' => array('nid'),
    ),
  );

  $schema['guifi_links'] = array(
    'comment' => 'devices/interfaces linked, one row per peer joined by guifi_links(id)',
    'fields' => array(
         'id' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
         'nid' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
         'device_id' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
         'interface_id' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
         'ipv4_id' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE),
         'link_type' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE),
         'routing' => array('type' => 'varchar', 'length' => '40', 'not null' => FALSE),
         'flag' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => 'Planned'),
         'hybrid' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('device_id', 'id'),
    'indexes' => array(
         'id' => array('id'),
         'device_index' => array('device_id'),
         'nid_index' => array('nid'),
    ),
  );

  $schema['guifi_interfaces'] = array(
    'comment' => 'describes interfaces (network connectors) at the devices',
    'fields' => array(
         'id' => array('type' => 'serial', 'size' => 'medium', 'not null' => TRUE),
         'device_id' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'comment' => 'foreign key to guifi_devices(id)'),
         'radiodev_counter' => array('type' => 'int', 'size' => 'tiny', 'not null' => FALSE, 'comment' => 'if not NULL, foreign key to guifi_radios(radiodev_counter)'),
         'etherdev_counter' => array('type' => 'int', 'size' => 'tiny', 'not null' => FALSE, 'comment' => 'if not NULL, foreign key to guifi_radios(etherdev_counter)'),
         'interface_class' => array('type' => 'varchar', 'length' => 40, 'NOT NULL' => FALSE, 'comment' => 'radio, ethernet, bridge, bonding, vlan, wds/p2p, virtualAP, tunnels ...'),
         'interface_type' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE),
         'related_interfaces' => array('type' => 'varchar', 'length' => 120, 'NOT NULL' => FALSE, 'comment' => 'FK to parent interfaces (vlans, bondings, bridges...'),
         'mac' => array('type' => 'varchar', 'length' => '20', 'not null' => TRUE, 'default' => '00:00:00:00:00:00'),
         'connector_type' => array('type' => 'varchar', 'length' => 10, 'comment' => 'connector type (RJ45,FO LX,SC...)'),
         'vlan' => array('type' => 'varchar', 'length' => 10, 'comment' => 'vlan (if have)'),
         'comments' => array('type' => 'varchar', 'length' => 64, 'comment' => 'Additional info/comments'),
         'connto_did' => array('type' => 'int', 'size' => 'medium', 'not null' => FALSE, 'comment' => 'connected to (device)'),
         'connto_iid' => array('type' => 'int', 'size' => 'medium', 'not null' => FALSE, 'comment' => 'connected to (interface)')),
    'primary key' => array('device_id', 'id'),
    'indexes' =>  array(
         'id' => array('id'),
    ),
  );

  $schema['guifi_radios'] = array(
    'comment' => 'describes wireless radios available on the guifi_devices',
    'fields' => array(
         'id' => array('type' => 'serial', 'not null' => TRUE,'comment' => 'primary key 1st column and foreign key to guifi_devices(id)'),
         'radiodev_counter' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 0, 'comment' => 'primary key 2nd column'),
         'etherdev_counter' => array('type' => 'int', 'size' => 'tiny', 'not null' => FALSE, 'comment' => ''),
         'nid' => array('comment' => 'foreign key to guifi_location(id)', 'type' => 'int', 'not null' => TRUE),
         'model_id' => array('type' => 'int', 'not null' => TRUE),
         'ssid' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE, 'default' => ''),
         'mode' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE),
         'protocol' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => '802.11bg'),
         'channel' => array('type' => 'int',  'not null' => FALSE),
         'chbandwith' => array('comment' => 'Channel Bandwith', 'type' => 'varchar', 'length' => '8', 'not null' => TRUE, 'default' => '20Mhz'),
         'antenna_angle' => array('type' => 'int', 'not null' => FALSE, 'default' => 0),
         'antenna_gain' => array('type' => 'int', 'not null' => FALSE),
         'antenna_azimuth' => array('type' => 'int', 'not null' => FALSE, 'default' => 360),
         'antenna_mode' => array('type' => 'varchar', 'length' => '5', 'not null' => TRUE),
         'mac' => array('type' => 'varchar', 'length' => '20'),
         'ly_mb_in' => array('type' => 'numeric', 'precision' => '10', 'scale' => '0', 'not null' => FALSE, 'default' => NULL),
         'ly_mb_out' => array('type' => 'numeric', 'precision' => '10', 'scale' => '0', 'not null' => FALSE, 'default' => NULL),
         'clients_accepted' => array('comment' => 'Yes, No', 'type' => 'varchar', 'length' => '5', 'not null' => FALSE, 'default' => 'Yes'),
         'fund_required' => array('comment' => 'Null n/d, free, yes', 'type' => 'varchar', 'length' => '5', 'not null' => FALSE),
         'fund_amount' => array('type' => 'numeric', 'not null'  => TRUE, 'default' => 0, 'precision' => '10', 'scale' => '2'),
         'fund_currency' => array('type' => 'varchar', 'length' => '10', 'not null'  => TRUE, 'default' => 'Euros'),
        ),
    'primary key' => array('id', 'radiodev_counter'),
    'indexes' => array(
         'nid' => array('nid')),
  );

  $schema['guifi_types'] = array(
    'comment' => 'used on web dialogs to decode values or validate values',
    'fields' => array(
         'id' => array('type' => 'serial', 'not null' => TRUE),
         'type' => array('type' => 'varchar', 'length' => '15', 'not null' => TRUE),
         'text' => array('type' => 'varchar', 'length' => '24', 'not null' => TRUE),
         'description' => array('type' => 'text', 'size' => 'big', 'not null' => TRUE),
         'relations' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE)),
    'primary key' => array('id', 'type'),
    'indexes' => array(
         'text' => array('text')),
  );

  $schema['guifi_services'] = array(
    'comment' => 'store guifi services',
    'fields' => array(
         'id' => array('type' => 'serial', 'not null' => TRUE),
         'nick' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => ''),
         'service_type' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => ''),
         'zone_id' => array('type' => 'int', 'not null' => FALSE, 'comment' => 'foreign key to guifi_zone(id)'),
         'device_id' => array('type' => 'int', 'not null' => FALSE, 'comment' => 'foreign key to guifi_device(id)'),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => FALSE),
         'status_flag' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => 'Planned'),
         'extra' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE),
         'user_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int', 'not null' => FALSE, 'default' => 0),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => FALSE)),
    'primary key' => array('id'),
    'indexes' => array(
        'zone_index' => array('zone_id'),
    ),
  );

  $schema['guifi_users'] = array(
    'comment' => 'stores user credentials assigned to nodes for proxy servers, or any other service',
    'fields' => array(
         'id' => array('type' => 'serial', 'unsigned' => TRUE, 'not null' => TRUE),
         'nid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE, 'default' => 0, 'comment' => 'foreign key to guifi_location(id)'),
         'services' => array('type' => 'text', 'size' => 'big', 'not null' => TRUE),
         'firstname' => array('type' => 'varchar', 'length' => '60', 'not null' => TRUE, 'default' => ''),
         'lastname' => array('type' => 'varchar', 'length' => '60', 'not null' => TRUE, 'default' => ''),
         'username' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => ''),
         'password' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE, 'default' => ''),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => FALSE),
         'extra' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE),
         'user_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'status' => array('type' => 'varchar', 'length' => 25, 'not null' => TRUE, 'default' => 'new', 'comment' => 'pending/approved/rejected'),
         'content_filters' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE, 'default' => NULL)),
    'primary key' => array('id'),
    'unique keys' => array(
         'username' => array('username')),
  );

  $schema['guifi_ipv4'] = array(
    'fields' => array(
         'id' => array('type' => 'int', 'not null' => TRUE, 'comment' => 'primary key 1st column, numbers the sequential order of each address into the same interface'),
         'interface_id' => array('type' => 'int', 'not null' => TRUE, 'default' => 0, 'comment' => 'primary key 2nd column and foreign key to guifi_interfaces(id)'),
         'ipv4' => array('type' => 'varchar', 'length' => '16', 'not null' => FALSE),
         'netmask' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE, 'default' => '255.255.255.0'),
         'ipv4_type' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'zone_id' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('interface_id', 'id'),
    'unique keys' => array(
         'ipv4' => array('ipv4')),
  );

  $schema['guifi_manufacturer'] = array(
    'comment' => 'device manufacturers',
    'fields' => array(
         'fid' => array('type' => 'serial', 'not null' => TRUE),
         'name' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => ''),
         'url' => array('type' => 'varchar', 'length' => '40', 'not null' => FALSE),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
         'user_created' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'user_changed' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE, 'default' => 0),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
         'timestamp_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('fid'),
  );

  $schema['guifi_model_specs'] = array(
    'comment' => 'device models',
    'fields' => array(
         'mid' => array('type' => 'serial', 'not null' => TRUE),
         'fid' => array('type' => 'int', 'not null' => TRUE, 'default' => 0, 'comment' => 'foreign key to guifi_manufacturer(fid)'),
         'model' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE, 'default' => ''),
         'model_class' => array('type' => 'varchar', 'length' => '240', 'not null' => TRUE, 'default' => 'wireless|router','comment'=>'device category (radio, router, switch...)'),
         'type' => array('type' => 'varchar', 'length' => '10', 'not null' => FALSE, 'comment' => 'Extern, PCI, PCMCIA'),
         'radiodev_max' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 1),
         'etherdev_max' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 1),
         'optoports_max' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 0),
         'rackeable' => array('type' => 'int', 'size' => 'tiny', 'not null' => TRUE, 'default' => 0,'comment'=> 'Rackeable (>0 true, # of Us)'),
         'AP' => array('type' => 'varchar', 'length' => '5', 'not null' => FALSE, 'comment' => 'Si, No'),
         'virtualAP' => array('type' => 'varchar', 'length' => '5', 'not null' => TRUE, 'default' => 'No', 'comment' => 'Yes, No'),
         'client' => array('type' => 'varchar', 'length' => '5', 'not null' => FALSE, 'comment' => 'Si, No, Hack'),
         'interfaces' => array('type' => 'varchar', 'length' => '240', 'not null' => FALSE,'comment' => 'Cable Interfaces'),
         'winterfaces' => array('type' => 'varchar', 'length' => '240', 'not null' => FALSE,'comment' => 'Wireless Interfaces'),
         'opto_interfaces' => array('type' => 'varchar', 'length' => '240', 'not null' => FALSE,'comment'=> 'map to ethernet interafaces'),
         'url' => array('type' => 'varchar', 'length' => '240', 'not null' => FALSE),
         'comments' => array('type' => 'varchar', 'length' => '240', 'not null' => FALSE),
         'supported' => array('type' => 'varchar', 'length' => '25', 'not null' => TRUE, 'default' => 'Yes', 'comment' => 'Yes, No'),
         'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
         'user_created' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE),
         'user_changed' => array('type' => 'int',  'size' => 'medium', 'not null' => TRUE),
         'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
         'timestamp_changed' => array('type' => 'int', 'not null' => TRUE)),
    'primary key' => array('mid'),
  );

  $schema['guifi_dns_domains'] = array(
    'comment' => 'store guifi dns domains',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'sid' => array('type' => 'int', 'not null' => TRUE),
      'name' => array('type' => 'varchar', 'length' => '40', 'not null' => TRUE),
      'type' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE),
      'public' => array('type' => 'varchar', 'length' => '5', 'not null' => TRUE, 'default' => 'yes'),
      'ipv4' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE),
      'defipv4' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE),
      'defipv6' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE),
      'mname' => array('type' => 'varchar', 'length' => '32', 'not null' => TRUE),
      'scope' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE),
      'management' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE),
      'allow' => array('type' => 'varchar', 'length' => '24', 'not null' => TRUE),
      'externalmx' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE),
      'externalns' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE),
      'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
      'comment' => array('type' => 'text', 'size' => 'big', 'not null' => FALSE),
      'user_created' => array('type' => 'int', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE)),
    'primary key' => array('id'),
  );

  $schema['guifi_dns_hosts'] = array(
    'comment' => 'store guifi dns hosts',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'counter' => array('type' => 'int', 'not null' => TRUE),
      'host' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE),
      'ipv4' => array('type' => 'varchar', 'length' => '16', 'not null' => TRUE),
      'ipv6' => array('type' => 'varchar', 'length' => '128', 'not null' => TRUE),
      'aliases' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
      'options' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE)),
    'primary key' => array('id', 'counter'),
  );

  $schema['guifi_api_tokens'] = array(
    'comment' => 'store guifi api tokens',
    'fields' => array(
      'uid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
      'token' => array('type' => 'varchar', 'length' => '255', 'not null' => TRUE),
      'created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'rand_key' => array('type' => 'int', 'not null' => TRUE)),
    'primary key' => array('uid'),
  );

  $schema['guifi_firmware'] = array (
    'comment' => 'have the supported firmwares, status and describes their capabilities',
    'fields'  => array(
      'id'    => array('type' => 'serial', 'not null' => TRUE),
      'nom'   => array('type' => 'varchar', 'length' => '45', 'not null' => TRUE),
      'descripcio'=>array('type' => 'varchar', 'length' => '45', 'not null' => TRUE),
      'relations' => array('type' => 'varchar', 'length' => '45'),
      'managed' => array('type' => 'varchar', 'length' => '100'),
      'enabled'   => array('type' => 'int', 'size' => 'tiny','not null' => FALSE, 'default' => 0),
      'notification' => array('type' => 'varchar', 'length' => '1024', 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE)),
    'primary key' => array('id'),
   );

  $schema['guifi_maintainers'] = array(
    'comment' => 'device maintainers',
    'fields' => array(
      'id' => array('type' => 'int', 'not null'  => TRUE, 'default' => 0, 'disp-width' => '11'),
      'supplier_id' => array('type' => 'int', 'unsigned' => TRUE, 'not null'  => TRUE, 'disp-width' => '11', 'default' => 0, 'comment' => 'Foreign key to supplier'),
      'subject_id' => array('type' => 'int', 'unsigned' => TRUE, 'not null'  => TRUE, 'disp-width' => '11', 'default' => 0, 'comment' => 'Foreign key to subject maintained (zone/node/device...)'),
      'subject_type' => array('type' => 'varchar', 'length' => 15, 'not null'  => TRUE, 'default' => '', 'comment' => 'subject type (values zone, node, device....)'),
      'commitment' => array('type' => 'varchar', 'length' => 15, 'not null'  => TRUE, 'default' => '', 'comment' => 'type of commitment: volunteer, FO, Wireless...'),
      'sla' => array('type' => 'varchar', 'length' => 15, 'not null'  => TRUE, 'default' => '', 'comment' => 'SLA: bone, 24x7, 8x5...'),
      'sla_resp' => array('type' => 'int', 'size'=>'small','not null'  => FALSE, 'comment' => 'Objective for response time' ),
      'sla_fix' => array('type' => 'int', 'size'=>'small','not null'  => FALSE,  'comment' => 'Objective for solving time' ),
      'weight' => array('type' => 'int', 'size'=>'small','not null'  => FALSE),
      'comment' => array('type' => 'text', 'not null'  => false),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => 0),
      'user_changed' => array('type' => 'int', 'size' => 'medium',' not null' => FALSE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'timestamp_changed' => array('type' => 'int', 'not null' => FALSE),
      ),
    'primary key' => array('id'),
  );

  $schema['guifi_funders'] = array(
    'comment' => 'device funders',
    'fields' => array(
      'id' => array('type' => 'int', 'not null'  => TRUE, 'default' => 0, 'disp-width' => '11'),
      'supplier_id' => array('type' => 'int', 'unsigned' => TRUE, 'not null'  => false, 'disp-width' => '11', 'default' => 0, 'comment' => 'Foreign key to supplier'),
      'user_id' => array('type' => 'int', 'size' => 'medium', 'unsigned' => TRUE, 'not null'  => false, 'disp-width' => '11', 'default' => 0, 'comment' => 'Foreign key to userid'),
      'comment' => array('type' => 'text', 'not null'  => TRUE),
//      'removed' => array('type' => 'int', 'size'=>'small','not null'  => TRUE, 'default' => FALSE),
      'subject_id' => array('type' => 'int', 'unsigned' => TRUE, 'not null'  => TRUE, 'disp-width' => '11', 'default' => 0, 'comment' => 'Foreign key to subject maintained (node/device...)'),
      'subject_type' => array('type' => 'varchar', 'length' => 15, 'not null'  => TRUE, 'default' => '', 'comment' => 'subject type (values node, device....)'),
      'weight' => array('type' => 'int', 'size'=>'small','not null'  => FALSE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => 0),
      'user_changed' => array('type' => 'int', 'size' => 'medium',' not null' => FALSE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'timestamp_changed' => array('type' => 'int', 'not null' => FALSE),
      ),
    'primary key' => array('id'),
  );


  $schema['guifi_caracteristica'] = array(
    'comment' => 'Caracteristiques',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'nom' => array('type' => 'varchar', 'length' => 45, 'not null' => TRUE),
      'tipus' => array('type' => 'varchar', 'length' => 11, 'not null' => TRUE),
      'notification' => array('type' => 'varchar', 'length' => 1024, 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE),
      ),
    'primary key' => array('id'),
  );


  $schema['guifi_configuracioUnSolclic'] = array(
    'comment' => 'UnSolclic Configurations',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'mid' => array('type' => 'int', 'not null' => TRUE),
      'fid' => array('type' => 'int', 'not null' => TRUE),
      'enabled' => array('type' => 'int', 'size' => 'tiny', 'unsigned' => TRUE, 'default' => 0),
      'snmp_id' => array('type' => 'varchar', 'length' => 32, 'not null' => TRUE, 'default' => 0),
      'plantilla' => array('type' => 'text'),
      'tipologia' => array('type' => 'int', 'size' => 'tiny', 'unsigned' => TRUE, 'not null' => TRUE, 'default' => 0),
      'notification' => array('type' => 'varchar', 'length' => 1024, 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => 0),
      'user_changed' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE, 'default' => 0),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'template_file' => array('type' => 'varchar', 'length' => 45),
      ),
    'primary key' => array('id'),
  );

  $schema['guifi_parametresConfiguracioUnsolclic'] = array(
    'comment' => 'Parameters forUnSolclic Configurations',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'pid' => array('type' => 'int', 'not null' => TRUE),
      'uscid' => array('type' => 'int', 'not null' => TRUE),
      'valor' => array('type' => 'varchar', 'length' => 255, 'not null' => TRUE),
      'dinamic' => array('type' => 'int', 'size' => 'tiny', 'unsigned' => TRUE, 'not null' => TRUE, 'default' => 0),
      'notification' => array('type' => 'varchar', 'length' => 1024, 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'size' => 'medium'),
      'timestamp_created' => array('type' => 'int'),
      'timestamp_changed' => array('type' => 'int'),
      ),
    'primary key' => array('id'),
  );


  $schema['guifi_parametres'] = array(
    'comment' => 'Parameters forUnSolclic',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'nom' => array('type' => 'varchar', 'length' => 45, 'not null' => FALSE),
      'default_value' => array('type' => 'varchar', 'length' => 45, 'not null' => FALSE),
      'origen' => array('type' => 'varchar', 'length' => 80, 'not null' => FALSE),
      'dinamic' => array('type' => 'int', 'size' => 'tiny', 'not null' => FALSE, 'default' => 0),
      'notification' => array('type' => 'varchar', 'length' => 1024, 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE),
      ),
    'primary key' => array('id'),
  );

 $schema['guifi_parametresFirmware'] = array(
    'comment' => 'Parameters firmware',
    'fields' => array(
      'id' => array('type' => 'serial', 'not null' => TRUE),
      'fid' => array('type' => 'int', 'not null' => FALSE),
      'pid' => array('type' => 'int', 'not null' => FALSE),
      'notification' => array('type' => 'varchar', 'length' => 1024, 'not null' => TRUE),
      'user_created' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),
      'user_changed' => array('type' => 'int', 'size' => 'medium', 'not null' => TRUE),  
      'timestamp_created' => array('type' => 'int', 'not null' => TRUE),
      'timestamp_changed' => array('type' => 'int', 'not null' => TRUE),
      ),
    'primary key' => array('id'),
  );

  return $schema;
}

function guifi_install() {

  drupal_install_schema('guifi');

  // --
  // -- interface types
  // -- relation describes MAC (related to base MAC)
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'interface', 'Lan', 'Device base address (Lan)', '0');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'interface', 'wLan/Lan', 'Device lan & wlan (bridged)', '2');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'interface', 'wLan', 'wireless lan', '2');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'interface', 'Wan', 'Wan', '1');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'interface', 'wds/p2p', 'P2P Wds', '2');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('6', 'interface', 'vlan', 'Virtual network over Lan', '0');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7', 'interface', 'vwan', 'Virtual network over Wan', '1');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8', 'interface', 'vwlan', 'Virtual network over wLan', '2');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('9', 'interface', 'vlan2', 'vlan #2 (plugged into port #2)', '4');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('10', 'interface', 'vlan3', 'vlan #3 (plugged into port #3)', '5');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('11', 'interface', 'vlan4', 'vlan #4 (plugged into port #4)', '6');");
  //db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('9999', 'interface', 'vlan1',   'vlan #1 (plugged into port #1)', '3');");

  // --
  // -- IPv4 types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'ipv4_types', '1', 'public', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'ipv4_types', '2', 'backbone', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'ipv4_types', '3', 'ad-hoc mesh - OLSR', 'kamikaze|freifunk-OLSR');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'ipv4_types', '4', 'ad-hoc mesh - BATMAN', 'kamikaze|freifunk-BATMAN');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'ipv4_types', '5', 'ad-hoc mesh - BMX', 'kamikaze');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('6', 'ipv4_types', '6', 'ad-hoc mesh - RouterOS', 'RouterOSv3.x');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7', 'ipv4_types', '7', 'mesh', NULL);");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8', 'ipv4_types', '8', 'reserved', NULL);");

  // --
  // -- radio mode types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'mode', 'ap', 'AP or AP with WDS', 'ap|client');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'mode', 'client', 'Wireless client', 'ap');");
  //db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'mode', 'bridge', 'Wireless Bridge', 'bridge');");
  //db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'mode', 'routedclient', 'Routed client',     'ap');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'mode', 'mesh', 'Mesh radio', NULL);");
  //db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('9999', 'mode', 'NAT Client', 'NAT Client', 'ap|client');");
  //db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8888', 'mode', 'Routed Client', 'Routed Client', 'ap|client');");
  //db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7777', 'mode', 'Bridged Client', 'Bridged  Client', 'ap|client');");

  // --
  // -- link types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'link', 'cable', 'Cable', 'vlan|vwan|vwlan|vlan1|vlan2|vlan3|vlan4|Lan|wLan/Lan|Wan');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'link', 'tunnel', 'Tunnel', 'tunnel');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'link', 'bridge', 'Wireless Bridge', 'wLan/Lan|Lan');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'link', 'wds', 'Wireless WDS', 'wds/p2p');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'link', 'ap/client', 'Wireless AP/Client', 'Wan/wLan|wLan/Lan');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('6', 'link', 'xPON', 'Passive Splitted Fibre Optics (xPON)', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7', 'link', 'DuplexFO', 'Duplex P2P', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8', 'link', 'SimplexFO', 'Simplex P2P', '');");

  // --
  // -- device types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'device', 'radio', 'Wireless device, like a router, bridge, AP...');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'device', 'phone', 'Voip handset, telephone');");
  db_query("-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'device', 'mobile', 'Mobile device. like a laptop or pda');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'device', 'server', 'Server computer');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'device', 'nat', 'Firewall, private Network behind a NAT');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'device', 'ADSL', 'ADSL router or device providing internet access');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'device', 'cam', 'Network camera. Live view.');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('8', 'device', 'generic', 'Any device that uses a public IP (PC, game console, laptop, pda..)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('9', 'device', 'confine', 'Node Confine/Clommunity');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('10', 'device', 'onu', 'xPON ONU User Unit (Final)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('11', 'device', 'olt', 'xPON OLT Concentrator (Terminal)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('12', 'device', 'splitter', 'xPON Splitter');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('13', 'device', 'fomconv', 'FO Media Converter');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('14', 'device', 'torpedo', 'Torpedo - Joint enclosure');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('15', 'device', 'switch', 'Switch');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('16', 'device', 'rack', 'Rack');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('17', 'device', 'ppanel','patch panel');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('18', 'device', 'ups', 'Uninterrumpible Power Supply (UPS)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('19', 'device', 'generator', 'Power generator source');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('20', 'device', 'solar', 'Solar Panel');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('21', 'device', 'battery', 'Battery');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('22', 'device', 'breaker','Circuit breakers / Surge protectors');");

  // --
  // -- service types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'service', 'AP', 'Wireless connectivity for end users');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'service', 'ADSL', 'Open ADSL-type internet access');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'service', 'Proxy', 'Internet access trough a proxy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'service', 'DNS', 'Domain Name Server service');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'service', 'NTP', 'Network Time Protocol service');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'service', 'mail', 'Mail server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'service', 'web', 'Web server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('8', 'service', 'ftp', 'FTP or shared disk server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('9', 'service', 'p2p', 'Peer 2 Peer server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('10', 'service', 'asterisk', 'Asterisk VoIP PBX server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('11', 'service', 'radio', 'Radio broadcast');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('12', 'service', 'tv', 'TV broadcast');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('13', 'service', 'irc', 'IRC (chat) server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('14', 'service', 'IM', 'Instant Messaging, jabber server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('15', 'service', 'cam', 'Network camera with live view.');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('16', 'service', 'svn', 'Subversion/CVS repository.');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('17', 'service', 'meteo', 'Weather station.');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('18', 'service', 'apt-cache', 'Linux distribution cache.');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('19', 'service', 'wol', 'Wake-on-lan');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('20', 'service', 'iperf', 'iperf bandwidth test');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('21', 'service', 'teamspeak', 'TeamSpeak Server - Voice conference');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('22', 'service', 'games', 'Generic games server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('23', 'service', 'SNPgraphs', 'SNP graph server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('24', 'service', 'Streaming', 'Videoconferènia i/o Streaming');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('25', 'service', 'VPN', 'Virtual Private Network');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('26', 'service', 'LDAP', 'LDAP Server');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('27', 'service', 'LogServer', 'Ip log Server');");


  // --
  // -- status flag types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'status', 'Planned',  'Planned');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'status', 'Reserved', 'Reserved');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'status', 'Building', 'Building');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'status', 'Testing',  'Testing');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'status', 'Working',  'Online');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'status', 'Dropped',  'Dropped');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'status', 'Inactive',  'Inactive');");

  // --
  // -- protocol types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'protocol'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'protocol', '802.11a', '802.11a (1-54Mbps - 5Ghz)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'protocol', '802.11b', '802.11b (1-11Mbps - 2.4Ghz)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'protocol', '802.11g', '802.11g (2-54Mbps - 2.4Ghz)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'protocol', '802.11n', '802.11n - MIMO (1-125Mbps - 2.4/5Ghz)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'protocol', 'WiMAX', '802.16a - WiMAX (1-125Mbps - 2-8Ghz)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'protocol', 'legacy', 'legacy/proprietary protocol');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'protocol', '802.11ac', '802.11ac - MIMO (1-125Mbps - Ghz)');");

  // --
  // -- firmware types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'firmware'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'firmware', 'n/a', 'not available', NULL);");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'firmware', 'Alchemy', 'Alchemy from sveasoft', 'WRT54Gv1-4|WRT54GSv1-2');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'firmware', 'Talisman', 'Talisman from sveasoft', 'WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'firmware', 'DD-WRTv23', 'DD-WRTv23Beta2 from BrainSlayer', 'WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|Asus WL-500xx|WHR-HP-G54, WHR-G54S|NanoStation2|NanoStation5|NanoStation Loco2|NanoStation Loco5|Bullet2|Bullet5|RouterStation|RouterStationPro|Avila GW2348-4');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'firmware', 'DD-guifi', 'DD-guifi from Miquel Martos', 'WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|WHR-HP-G54, WHR-G54S');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('6', 'firmware', 'RouterOSv2.9', 'RouterOS 2.9 from Mikrotik', 'Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153|Supertrasto guifiBUS guifi.net');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7', 'firmware', 'whiterussian', 'OpenWRT-whiterussian', 'WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|Wrap|Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8', 'firmware', 'kamikaze', 'OpenWRT kamikaze','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|Meraki/Fonera|Wrap|Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153|Supertrasto guifiBUS guifi.net|NanoStation2|NanoStation5|NanoStation Loco2|NanoStation Loco5|Bullet2|Bullet5|RouterStation|RouterStationPro|Avila GW2348-4|Asus WL-500xx|Alix1|Alix2|Alix3');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('9', 'firmware', 'Freifunk-BATMAN', 'OpenWRT-Freifunk-v1.6.16 with B.A.T.M.A.N', 'WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|WHR-HP-G54, WHR-G54S');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('10', 'firmware', 'RouterOSv3.x', 'RouterOS 3.x from Mikrotik', 'Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153|Supertrasto guifiBUS guifi.net|Routerboard 600|Routerboard 411|Routerboard 333|Routerboard 433');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('11', 'firmware', 'AirOsv221', 'Ubiquti AirOs 2.2.1', 'NanoStation2|NanoStation5|NanoStation Loco2|NanoStation Loco5|Bullet2|Bullet5')");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('12', 'firmware', 'Freifunk-OLSR', 'OpenWRT-Freifunk-v1.6.16 with OLSR', 'WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|WHR-HP-G54, WHR-G54S');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('13', 'firmware', 'AirOsv30', 'Ubiquti AirOs 3.0', 'NanoStation2|NanoStation5|NanoStation Loco2|NanoStation Loco5|Bullet2|Bullet5')");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('14', 'firmware', 'RouterOSv4.0+', 'RouterOS 4.0 to 4.6 from Mikrotik', 'Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153|Supertrasto guifiBUS guifi.net|Routerboard 600|Routerboard 411|Routerboard 333|Routerboard 433|Routerboard 800');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('15', 'firmware', 'AirOsv52', 'Ubiquti AirOs 5.2', 'AirMaxM2 Rocket/Nano/Loco|AirMaxM5 Rocket/Nano/Loco|AirMaxM2 Bullet/PwBrg/AirGrd/NanoBr|AirMaxM5 Bullet/PwBrg/AirGrd/NanoBr');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('16', 'firmware', 'RouterOSv4.7+', 'RouterOS 4.7 or newer from Mikrotik', 'Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153|Supertrasto guifiBUS guifi.net|Routerboard 600|Routerboard 411|Routerboard 333|Routerboard 433|Routerboard 800|Routerboard 750/750G');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('17', 'firmware', 'GuifiStationOS1.0', 'GuifiStationOS v1.0 from Setup Informatica', 'GuifiStation2|GuifiStation5');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('18', 'firmware', 'gsffirm', 'Firmware de GràciaSenseFils MANET', 'Alix2|Alix3|WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|Asus WL-500xx|WHR-HP-G54, WHR-G54S|NanoStation2|NanoStation5|NanoStation Loco2|NanoStation Loco5|Bullet2|Bullet5|RouterStation|RouterStationPro|Meraki/Fonera');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('19', 'firmware', 'RouterOSv5.x', 'RouterOS 5.x or newer from Mikrotik', 'Routerboard 532|Routerboard 133C|Routerboard 133|Routerboard 112|Routerboard 153|Supertrasto guifiBUS guifi.net|Routerboard 600|Routerboard 411|Routerboard 333|Routerboard 433|Routerboard 800|Routerboard 750/750G');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('20', 'firmware', 'AirOsv3.6+', 'Ubiquti AirOs 3.6+', 'NanoStation2|NanoStation5|NanoStation Loco2|NanoStation Loco5|Bullet2|Bullet5')");

  // --
  // -- antenna types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'antenna', '0', 'original/integrated');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'antenna', '360', 'omnidirectional');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'antenna', '6', 'yagi/directive');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'antenna', '90', 'sector 90 degrees');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'antenna', '120', 'sector 120 degrees');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'antenna', '90', 'patch 90 degrees');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'antenna', '60', 'patch 60 degrees');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('8', 'antenna', '30', 'patch 30 degrees');");

  // --
  // -- orientation (bearing) types
  // --
/*
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'N',   'North');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'NE',  'North east');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'E',   'East');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'SE',  'South east');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'S',   'South');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'SW',  'South west');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'W',   'West');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'NW',  'North east');
-- INSERT INTO {guifi_types} (id, type, text, description) VALUES ('bearing', 'all', '360 degrees');
*/
  // --
  // -- Time zones
  // --

  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'tz', '-12 1 0', '(GMT-12:00) Kwajalein');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'tz', '-11 1 0', '(GMT-11:00) Midway Island, Samoa');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'tz', '-10 1 0', '(GMT-10:00) Hawaii');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'tz', '-09 1 1', '(GMT-09:00) Alaska');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'tz', '-08 1 1', '(GMT-08:00) Pacific Time (USA &amp; Canada)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'tz', '-07 1 0', '(GMT-07:00) Arizona');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'tz', '-07 2 1', '(GMT-07:00) Mountain Time (USA &amp; Canada)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('8', 'tz', '-06 1 0', '(GMT-06:00) Mexico');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('9', 'tz', '-06 2 1', '(GMT-06:00) Central Time (USA &amp; Canada)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('10', 'tz', '-05 1 0', '(GMT-05:00) Indiana East, Colombia, Panama');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('11', 'tz', '-05 2 1', '(GMT-05:00) Eastern Time (USA &amp; Canada)');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('12', 'tz', '-04 1 0', '(GMT-04:00) Bolivia, Venezuela');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('13', 'tz', '-04 2 1', '(GMT-04:00) Atlantic Time (Canada), Brazil West');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('14', 'tz', '-03.5 1 1', '(GMT-03:30) Newfoundland');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('15', 'tz', '-03 1 0', '(GMT-03:00) Guyana');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('16', 'tz', '-03 2 1', '(GMT-03:00) Brazil East, Greenland');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('17', 'tz', '-02 1 0', '(GMT-02:00) Mid-Atlantic');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('18', 'tz', '-01 1 2', '(GMT-01:00) Azores');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('19', 'tz', '+00 1 0', '(GMT) Gambia, Liberia, Morocco');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('20', 'tz', '+00 2 2', '(GMT) England');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('21', 'tz', '+01 1 0', '(GMT+01:00) Tunisia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('22', 'tz', '+01 2 2', '(GMT+01:00) Gurb, France, Germany, Italy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('23', 'tz', '+02 1 0', '(GMT+02:00) South Africa');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('24', 'tz', '+02 2 2', '(GMT+02:00) Greece, Ukraine, Romania, Turkey');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('25', 'tz', '+03 1 0', '(GMT+03:00) Iraq, Jordan, Kuwait');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('26', 'tz', '+04 1 0', '(GMT+04:00) Armenia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('27', 'tz', '+05 1 0', '(GMT+05:00) Pakistan, Russia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('28', 'tz', '+06 1 0', '(GMT+06:00) Bangladesh, Russia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('29', 'tz', '+07 1 0', '(GMT+07:00) Thailand, Russia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('30', 'tz', '+08 1 0', '(GMT+08:00) China, Hong Kong, Australia Western');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('31', 'tz', '+08 2 0', '(GMT+08:00) Singapore, Taiwan, Russia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('32', 'tz', '+09 1 0', '(GMT+09:00) Japan, Korea');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('33', 'tz', '+09.5 1 4', '(GMT+09:30) Australia Central');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('34', 'tz', '+10 1 0', '(GMT+10:00) Guam, Russia');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('35', 'tz', '+10 2 4', '(GMT+10:00) Australia Eastern');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('36', 'tz', '+11 1 0', '(GMT+11:00) Solomon Islands');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('37', 'tz', '+12 1 0', '(GMT+12:00) Fiji');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('38', 'tz', '+12 2 4', '(GMT+12:00) New Zealand');");

  // --
  // -- Wireless Channels
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'channel'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'channel', '0', 'Auto 2.4GHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'channel', '1', '1 - 2412 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'channel', '2', '2 - 2417 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'channel', '3', '3 - 2422 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'channel', '4', '4 - 2427 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('6', 'channel', '5', '5 - 2432 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7', 'channel', '6', '6 - 2437 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8', 'channel', '7', '7 - 2442 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('9', 'channel', '8', '8 - 2447 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('10', 'channel', '9', '9 - 2452 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('11', 'channel', '10', '10 - 2457 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('12', 'channel', '11', '11 - 2462 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('13', 'channel', '12', '12 - 2467 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('14', 'channel', '13', '13 - 2472 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('15', 'channel', '14', '14 - 2477 MHz', '802.11b|802.11g|802.11n');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('16', 'channel', '5000', 'Auto 5GHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('17', 'channel', '5180', '36 - 5180MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('18', 'channel', '5200', '40 - 5200MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('19', 'channel', '5220', '44 - 5220MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('20', 'channel', '5240', '48 - 5240MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('21', 'channel', '5260', '52 - 5260MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('22', 'channel', '5280', '56 - 5280MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('23', 'channel', '5300', '60 - 5300MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('24', 'channel', '5320', '64 - 5320MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('25', 'channel', '5500', '100 - 5500MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('26', 'channel', '5520', '104 - 5520MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('27', 'channel', '5540', '108 - 5540MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('28', 'channel', '5560', '112 - 5560MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('29', 'channel', '5580', '116 - 5580MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('30', 'channel', '5600', '120 - 5600MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('31', 'channel', '5620', '124 - 5620MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('32', 'channel', '5640', '128 - 5640MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('33', 'channel', '5660', '132 - 5660MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('34', 'channel', '5680', '136 - 5680MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('35', 'channel', '5700', '140 - 5700MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('36', 'channel', '5185', '37 - 5185MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('37', 'channel', '5190', '38 - 5190MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('38', 'channel', '5195', '39 - 5195MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('39', 'channel', '5205', '41 - 5205MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('40', 'channel', '5210', '42 - 5210MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('41', 'channel', '5215', '43 - 5215MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('42', 'channel', '5225', '45 - 5225MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('43', 'channel', '5230', '46 - 5230MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('44', 'channel', '5235', '47 - 5235MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('45', 'channel', '5245', '49 - 5245MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('46', 'channel', '5250', '50 - 5250MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('47', 'channel', '5255', '51 - 5255MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('48', 'channel', '5265', '53 - 5265MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('49', 'channel', '5270', '54 - 5270MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('50', 'channel', '5275', '55 - 5275MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('51', 'channel', '5285', '57 - 5285MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('52', 'channel', '5290', '58 - 5290MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('53', 'channel', '5295', '59 - 5295MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('54', 'channel', '5305', '61 - 5305MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('55', 'channel', '5310', '62 - 5310MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('56', 'channel', '5315', '63 - 5315MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('57', 'channel', '5505', '101 - 5505MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('58', 'channel', '5510', '102 - 5510MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('59', 'channel', '5515', '103 - 5515MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('60', 'channel', '5525', '105 - 5525MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('61', 'channel', '5530', '106 - 5530MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('62', 'channel', '5535', '107 - 5535MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('63', 'channel', '5545', '109 - 5545MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('64', 'channel', '5550', '110 - 5550MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('65', 'channel', '5555', '111 - 5555MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('66', 'channel', '5565', '113 - 5565MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('67', 'channel', '5570', '114 - 5570MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('68', 'channel', '5575', '115 - 5575MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('69', 'channel', '5585', '117 - 5585MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('70', 'channel', '5590', '118 - 5590MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('71', 'channel', '5595', '119 - 5595MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('72', 'channel', '5605', '121 - 5605MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('73', 'channel', '5610', '122 - 5610MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('74', 'channel', '5615', '123 - 5615MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('75', 'channel', '5625', '125 - 5625MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('76', 'channel', '5630', '126 - 5630MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('77', 'channel', '5635', '127 - 5635MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('78', 'channel', '5645', '129 - 5645MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('79', 'channel', '5650', '130 - 5650MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('80', 'channel', '5655', '131 - 5655MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('81', 'channel', '5665', '133 - 5665MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('82', 'channel', '5670', '134 - 5670MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('83', 'channel', '5675', '135 - 5675MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('84', 'channel', '5685', '137 - 5685MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('85', 'channel', '5690', '138 - 5690MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('86', 'channel', '5695', '139 - 5695MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('87', 'channel', '0000', 'Auto 2-8GHz', 'WiMAX');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('88', 'channel', '0', '10Ghz auto', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('89', 'channel', '10308', '48 - 10308MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('90', 'channel', '10322', '51 - 10322MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('91', 'channel', '10336', '54 - 10336MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('92', 'channel', '10350', '57 - 10350MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('93', 'channel', '10364', '59 - 10364MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('94', 'channel', '10378', '62 - 10378MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('95', 'channel', '10392', '65 - 10392MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('96', 'channel', '10406', '68 - 10406MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('97', 'channel', '10490', '85 - 10490MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('98', 'channel', '10504', '87 - 10504MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('99', 'channel', '10518', '90 - 10518MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('100', 'channel', '10532', '93 - 10532MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('101', 'channel', '10546', '96 - 10546MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('102', 'channel', '10560', '99 - 10560MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('103', 'channel', '10574', '101 - 10574MHz', 'Legacy');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('104', 'channel', '5745', '149 - 5745MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('105', 'channel', '5765', '153 - 5765MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('106', 'channel', '5785', '157 - 5785MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('107', 'channel', '5805', '161 - 5805MHz', '802.11a|802.11n|802.11ac');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('108', 'channel', '5825', '165 - 5825MHz', '802.11a|802.11n|802.11ac');");

  // --
  // -- Wireless channel bandwith
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES " .
                "('1', 'chbandwith', '5Mhz', '5Mhz')," .
                "('2', 'chbandwith', '7Mhz', '7Mhz')," .
                "('3', 'chbandwith', '8Mhz', '8Mhz')," .
                "('4', 'chbandwith', '10Mhz', '10Mhz')," .
                "('5', 'chbandwith', '14Mhz', '14Mhz')," .
                "('6', 'chbandwith', '20Mhz', '20Mhz')," .
                "('7', 'chbandwith', '28Mhz', '28Mhz')," .
                "('8', 'chbandwith', '30Mhz', '30Mhz')," .
                "('9', 'chbandwith', '40Mhz', '40Mhz')," .
                "('10', 'chbandwith', '50Mhz', '50Mhz')," .
                "('11', 'chbandwith', '60Mhz', '60Mhz')," .
                "('12', 'chbandwith', '70Mhz', '70Mhz')," .
                "('13', 'chbandwith', '80Mhz', '80Mhz')," .
                "('14', 'chbandwith', '160Mhz', '160Mhz');");

  // --
  // -- Routing methods
  // -- Relations contains supported firmwares
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'routing', 'n/a', 'None', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'routing', 'Static', 'Static routing', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'routing', 'Gateway', 'Gateway to AP', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'routing', 'OSPF', 'OSPF', 'Alchemy|Talisman|DD-WRTv23|DD-guifi|RouterOSv2.9|RouterOSv3.x');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('5', 'routing', 'BGP', 'BGP', 'Alchemy|Talisman|DD-WRTv23|DD-guifi|RouterOSv2.9|RouterOSv3.x');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('6', 'routing', 'OLSR', 'OLSR', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('7', 'routing', 'OLSR-NG', 'OLSR-NG', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('8', 'routing', 'BATMAN', 'BATMAN', '');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('9', 'routing', 'RIP', 'RIP', '');");


  // --
  // -- ad-hoc dynamic protocols
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('1', 'adhoc', 'OLSR', 'ad-hoc mesh - OLSR', 'kamikaze|freifunk-OLSR');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('2', 'adhoc', 'OLSR-NG', 'ad-hoc mesh - OLSR-NG', 'kamikaze');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('3', 'adhoc', 'BATMAN', 'ad-hoc mesh - BATMAN', 'kamikaze|freifunk-BATMAN');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES ('4', 'adhoc', 'RouterOS', 'ad-hoc mesh - RouterOS', 'RouterOSv3.x');");

  // Antenna Gain Types
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('1', 'antenna_gain', '5', '5', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('2', 'antenna_gain', '6', '6', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('3', 'antenna_gain', '7', '7', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('4', 'antenna_gain', '8', '8', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('5', 'antenna_gain', '9', '9', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('6', 'antenna_gain', '10', '10', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('7', 'antenna_gain', '11', '11', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('8', 'antenna_gain', '12', '12', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('9', 'antenna_gain', '13', '13', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('10', 'antenna_gain', '14', '14', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('11', 'antenna_gain', '15', '15', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('12', 'antenna_gain', '16', '16', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('13', 'antenna_gain', '17', '17', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('14', 'antenna_gain', '18', '18', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('15', 'antenna_gain', '19', '19', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('16', 'antenna_gain', '20', '20', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('17', 'antenna_gain', '21', '21', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('18', 'antenna_gain', '22', '22', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('19', 'antenna_gain', '23', '23', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('20', 'antenna_gain', '24', '24', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('21', 'antenna_gain', '25', '25', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('22', 'antenna_gain', '26', '26', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('23', 'antenna_gain', '27', '27', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('24', 'antenna_gain', '28', '28', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('25', 'antenna_gain', '29', '29', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('26', 'antenna_gain', '30', '30', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('27', 'antenna_gain', '31', '31', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('28', 'antenna_gain', '32', '32', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('29', 'antenna_gain', '33', '33', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('30', 'antenna_gain', '34', '34', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('31', 'antenna_gain', '35', '35', NULL);");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('32', 'antenna_gain', '36', '36', '');");
  db_query("INSERT INTO `guifi_types` (`id`, `type`, `text`, `description`, `relations`) VALUES ('33', 'antenna_gain', 'more...', 'more...', NULL);");

  // --
  // -- Contribution types
  // --

  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'contribution', '',  'Not defined, contact admins');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'contribution', 'free',   'Free - No funding required');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'contribution', 'yes', 'Funding required');");

  // --
  // -- Volcant dades de la taula guifi_manufacturer
  // --
  update_sql("TRUNCATE guifi_manufacturer");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (1, 'Other', NULL, 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (2, 'Linksys', 'http://www.linksys.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (8, 'Mikrotik', 'http://mikrotik.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (9, 'Buffalo', 'http://www.buffalotech.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (10, 'Ubiquiti', 'http://www.ubnt.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (11, 'Meraki', 'http://meraki.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (12, 'Gateworks', 'http://www.gateworks.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (13, 'Asus', 'http://asus.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (14, 'Pccengines', 'http://www.pcengines.ch', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (15, 'Setup Informatica', 'http://www.setup.cat', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (100, 'DLink', 'http://www.dlink.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (101, 'Deliberant', 'http://www.deliberant.com', 'webmestre@guifi.net');");
  db_query("INSERT INTO `guifi_manufacturer` (`fid`, `name`, `url`, `notification` ) VALUES (102, 'TP-Link', 'http://www.tp-link.com', 'webmestre@guifi.net');");

  // --
  // -- guifi_model_specs
  // --
  update_sql("TRUNCATE guifi_model_specs");
  db_query("INSERT INTO `guifi_model_specs` (`mid`, `fid`, `model`, `model_class`, `type`, `radiodev_max`, `etherdev_max`, `optoports_max`, `rackeable`, `AP`, `virtualAP`, `client`, `interfaces`, `winterfaces`, `opto_interfaces`, `url`, `comments`, `supported`, `notification`, `user_created`, `user_changed`, `timestamp_created`, `timestamp_changed`) VALUES
(47, 10, 'AirMaxM2 Bullet/PwBrg/AirGrd/NanoBr', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://ubnt.com/airmax', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1415288717),
(46, 10, 'AirMaxM5 Rocket/Nano/Loco', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://ubnt.com/airmax', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1415288737),
(45, 10, 'AirMaxM2 Rocket/Nano/Loco', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://ubnt.com/airmax', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1415288752),
(43, 14, 'Alix3', 'wireless|router', 'Extern', 2, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0|eth1|eth2', 'wlan0|wlan1', NULL, 'http://www.pcengines.ch/alix3d.htm', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1450279561),
(44, 8, 'Routerboard 800', 'wireless|router', NULL, 8, 3, 0, 0, 'Yes', 'Yes', 'No', 'ether1|ether2|ether3', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6|wlan7|wlan8', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627537),
(57, 8, 'OmniTIK Uxx-5HnD', 'wireless|router', NULL, 1, 5, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3|ether4|ether5', 'wlan1', NULL, 'http://routerboard.com/RBOMNITIKUPA-5HnD', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1346166674, 1426627597),
(41, 14, 'Alix1', 'wireless|router', 'Extern', 1, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0|eth1|eth2', NULL, NULL, 'http://www.pcengines.ch/alix1d.htm', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1415288882),
(42, 14, 'Alix2', 'wireless|router', 'Extern', 2, 2, 0, 0, 'Yes', 'Yes', 'Yes', 'wLan/Lan|eth0|eth1|eth2', 'wlan0|wlan1', NULL, 'http://www.pcengines.ch/alix2d.htm', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1450279276),
(40, 13, 'Asus WL-500xx', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', 'No', 'Yes', 'Wan', NULL, NULL, 'http://asus.com/products.aspx?l1=29&l2=172&l3=743&l4=60&model=1277&modelmenu=1', 'Permet Firmwares de tercers', 'Yes', 'albertsarle@gmail.com', 0, 541, 0, 1344762289),
(39, 12, 'Avila GW2348-4', 'wireless|router', 'Extern', 4, 1, 0, 0, 'No', 'No', 'Si', 'Wan', NULL, NULL, 'http://www.gateworks.com/products/avila/gw2348-4.php', 'Permet Firmwares de tercers', 'Yes', '', 0, 0, 0, 0),
(38, 10, 'RouterStation', 'wireless|router', 'Extern', 3, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|wlan1|wlan2|eth0|eth1|eth2', NULL, NULL, 'http://www.ubnt.com/routerstation', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1352071734),
(37, 10, '5Ghz Nano/NanoLoco/Bullet/Lite/Pico', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', 'No', 'Yes', 'eth0', NULL, NULL, 'http://www.ubnt.com/products/loco.php', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1415287718),
(36, 10, '2,4Ghz Nano/NanoLoco/Bullet/Lite/Pico', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', 'No', 'Yes', 'eth0', NULL, NULL, 'http://www.ubnt.com/products/loco.php', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1415287734),
(31, 8, 'Routerboard 433', 'wireless|router', NULL, 6, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627824),
(30, 11, 'Meraki/Fonera', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Si', 'Yes', 'Si', 'wLan/Lan', NULL, NULL, 'http://meraki.com', NULL, 'Yes', '', 0, 0, 0, 0),
(29, 8, 'Routerboard 411', 'wireless|router', NULL, 6, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627798),
(28, 8, 'Routerboard 333', 'wireless|router', NULL, 6, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627782),
(27, 8, 'Routerboard 600', 'wireless|router', 'Extern', 8, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6|wlan7|wlan8', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627883),
(24, 8, 'Supertrasto guifiBUS guifi.net', 'wireless|router', NULL, 20, 10, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6|wlan7|wlan8|wlan9|wlan10|wlan11|wlan12|wlan13|wlan14|wlan15|wlan16|wlan17|wlan18|wlan19|wlan20', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426628076),
(23, 8, 'Routerboard 153', 'wireless|router', NULL, 3, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'wLan/Lan|ether2|ether3|ether4|ether5', 'wlan1|wlan2|wlan3', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627705),
(22, 8, 'Routerboard 112', 'wireless|router', NULL, 2, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1|wlan2', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627657),
(20, 8, 'Routerboard 133C', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627692),
(21, 8, 'Routerboard 133', 'wireless|router', NULL, 3, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1|wlan2|wlan3', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627677),
(19, 8, 'Routerboard 532', 'wireless|router', NULL, 4, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3', 'wlan1|wlan2|wlan3|wlan4', NULL, 'http://www.routerboard.com', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627861),
(18, 2, 'WRT54GSv4', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', '', 'Hack', 'wLan/Lan|vlan|vlan2|vlan3|vlan4|Wan', NULL, NULL, 'http://www.linksys.com/products/product.', 'El canvi de potència mode client i WDS, via hack.\r\nHacks disponibles: sveasoft (Satori, Alchemy...), OpenWRT, DD-WRT, ...', 'Yes', '', 0, 0, 0, 0),
(17, 2, 'WRT54GSv1-2', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', '', 'Hack', 'wLan/Lan|vlan2|vlan3|vlan4|Wan', NULL, NULL, 'http://www.linksys.com/products/product.', 'El canvi de potència, mode client i WDS, via hack.\r\nHacks disponibles: sveasoft (Satori, Alchemy...), OpenWRT, DD-WRT, ...', 'Yes', '', 0, 0, 0, 0),
(16, 2, 'WRT54GL', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', '', 'Hack', 'wLan/Lan|vlan|vlan2|vlan3|vlan4|Wan', NULL, NULL, 'http://www.linksys.com/products/product.', 'El canvi de potència, mode client i WDS, via hack.\r\nHacks disponibles: sveasoft (Satori, Alchemy...), OpenWRT, DD-WRT, ...', 'Yes', '', 0, 0, 0, 0),
(15, 9, 'WHR-HP-G54, WHR-G54S', 'wireless|router', 'Extern', 1, 1, 0, 0, 'No', '', 'Hack', 'wLan/Lan|vlan|vlan2|vlan3|vlan4|Wan', NULL, NULL, 'http://www.buffalo-technology.com/products/product-detail.php?productid=124&categoryid=28', 'El canvi de potència, mode client i WDS, via hack.', 'Yes', '', 0, 0, 0, 0),
(3, 99, 'Generic/Other', 'wireless|router|fiber|switch', NULL, 10, 10, 0, 0, 'Yes', 'No', 'Yes', 'eth0|eth1|eth2|eth3|eth4|eth5|eth6|eth7|eth8|eth9', 'wlan1|wlan2|wlan3|wlan4|wlan5|wlan6|wlan7|wlan8|wlan9|wlan10', NULL, 'none', 'To be used for unknown or not listed devices', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426628215),
(1, 2, 'WRT54Gv1-4', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Si', 'No', 'Hack', 'wLan/Lan|vlan|vlan2|vlan3|vlan4|Wan', NULL, NULL, 'http://www.linksys.com/products/product.', 'El canvi de potència, mode client i WDS, via hack.\r\nHacks disponibles: sveasoft (Satori, Alchemy...), OpenWRT...', 'Yes', '', 0, 0, 0, 0),
(48, 10, 'AirMaxM5 Bullet/PwBrg/AirGrd/NanoBr', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', 'ath0', NULL, 'http://ubnt.com/airmax', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426713048),
(49, 15, 'GuifiStation2', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Yes', 'No', 'Si', 'eth0|ath0', NULL, NULL, 'http://tienda.setupinformatica.com/wac/detalle.php?codigo=CPEGS2', 'Permet Firmwares de tercers', 'Yes', '', 0, 0, 0, 0),
(50, 15, 'GuifiStation5', 'wireless|router', 'Extern', 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'eth0|ath0', NULL, NULL, 'http://tienda.setupinformatica.com/wac/detalle.php?codigo=CPEGS5', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1311764826),
(51, 10, 'RouterStationPro', 'wireless|router', 'Extern', 3, 4, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|wlan1|wlan2|wan0|eth0|eth1|eth2', NULL, NULL, 'http://ubnt.com/rspro', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1352071721),
(52, 8, 'Routerboard 750/G', 'router', 'Extern', 0, 5, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3|ether4|ether5', NULL, NULL, 'http://www.routerboard.com/pricelist.php?showProduct=90', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627899),
(53, 8, 'Routerboard SXT 5HnD', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', NULL, 'http://www.routerboard.com/index.php?showProduct=108', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627955),
(54, 8, 'Routerboard 1100', 'router', NULL, 0, 13, 0, 0, 'Yes', 'Yes', 'No', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10|ether11|ether12|ether13', NULL, NULL, 'http://www.routerboard.com/index.php?showProduct=98', NULL, 'Yes', 'webmestre@guifi.net', 0, 1, 0, 1426627740),
(55, 8, 'Routerboard 493/G', 'wireless|router', NULL, 3, 9, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9', 'wlan1|wlan2|wlan3', NULL, 'http://www.routerboard.com/index.php?showProduct=108', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1312627558, 1426627845),
(56, 100, 'DIR-600 B1/B2', 'wireless|router', NULL, 1, 4, 0, 0, 'No', 'No', 'Yes', 'ra0', NULL, NULL, 'http://www.dlink.es/cs/Satellite?c=Product_C&childpagename=DLinkEurope-ES%2FDLProductCarouselMultiple&cid=1197381561250&p=119731', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1313257198, 1313257579),
(58, 8, 'Routerboard 2011', 'router', NULL, 0, 10, 0, 0, 'Yes', 'Yes', 'No', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10', NULL, '', 'http://routerboard.com/RB2011L-IN', NULL, 'Yes', 'webmestre@guifi.net', 8875, 163, 1346585353, 1426627723),
(59, 102, 'TL-WA7510N', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', NULL, NULL, 'http://www.tp-link.com/en/products/details/?categoryid=&model=TL-WA7510N', NULL, 'Yes', 'jrdi82@hotmail.com, webmestre@guifi.net', 8875, 1, 1346847734, 1370889535),
(60, 102, 'TL-WDR3600', 'wireless|router', NULL, 2, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://www.tp-link.com/en/products/details/?categoryid=&model=TL-WDR3600', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1370889155, 1415287751),
(61, 102, 'TL-WDR4300', 'wireless|router', NULL, 2, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://www.tp-link.com/en/products/details/?categoryid=&model=TL-WDR4300', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1370889394, 1415287855),
(62, 102, 'TL-WDR4900', 'wireless|router', NULL, 2, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://www.tp-link.com/en/products/details/?categoryid=&model=TL-WDR4900', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1370889497, 1415287995),
(63, 102, 'TL-WR2543ND', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', NULL, NULL, 'http://www.tp-link.com/en/products/details/?categoryid=&model=TL-WR2543ND', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1370890180, 1415288800),
(64, 102, 'TL-WR841N/ND', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|eth0', NULL, NULL, 'http://www.tp-link.com/en/search/?categoryid=1044&keywords=841N', NULL, 'Yes', 'webmestre@guifi.net', 1, 0, 1370890285, 0),
(65, 102, 'TL-WR842ND', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|eth0', NULL, NULL, 'http://www.tp-link.com/en/search/?keywords=842N', NULL, 'Yes', 'webmestre@guifi.net', 1, 0, 1370890327, 0),
(66, 102, 'TL-WR703N', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|eth0', NULL, NULL, 'http://www.tp-link.com/lk/search/?categoryid=1044&keywords=wr70', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1370890596, 1370890697),
(67, 102, 'TL-MR3020', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|eth0', NULL, NULL, 'http://www.tp-link.com/en/products/details/?model=TL-MR3020', NULL, 'Yes', 'webmestre@guifi.net', 1, 0, 1370890675, 0),
(68, 102, 'TL-MR3040', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'wlan0|eth0', NULL, NULL, 'http://www.tp-link.es/products/details/?model=TL-MR3040', NULL, 'Yes', 'webmestre@guifi.net', 1, 0, 1370890770, 0),
(69, 8, 'Routerboard SXT Lite2', 'wireless|router', NULL, 1, 1, 0, 0, 'No', 'No', 'Yes', 'ether1', 'wlan1', NULL, 'http://routerboard.com/RBSXT-2nDr2', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1381960363, 1426627973),
(70, 8, 'Routerboard SXT Lite5', 'wireless|router', NULL, 1, 1, 0, 0, 'No', 'No', 'Yes', 'ether1', 'wlan1', NULL, 'http://routerboard.com/RBSXT-5nDr2', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1381960624, 1426627986),
(71, 8, 'Routerboard Sextant', 'wireless|router', NULL, 1, 1, 0, 0, 'No', 'Yes', 'Yes', 'ether1', 'wlan1', NULL, 'http://www.mikrotik.com/', NULL, 'Yes', 'jrdi82@hotmail.com', 1, 1, 1388185734, 1426627942),
(72, 100, '24 ports (+4 SFP) generic DLINK switch', 'fiber|switch', NULL, 1, 24, 4, 1, NULL, 'No', NULL, NULL, NULL, '21|22|23|24', 'http://www.dlink.com/us/en/business-solutions/switching/managed-switches/layer-2/dgs-3420-52t-52-port-xstack-layer-2plus-managed', NULL, 'Yes', 'webmestre@guifi.net', 2, 2, 1400535136, 1400535150),
(73, 100, '48 ports (+4 SFP) generic DLINK switch', 'fiber|switch', NULL, 1, 48, 4, 1, NULL, 'No', NULL, NULL, NULL, '45|46|47|48', 'http://www.dlink.com/us/en/business-solutions/switching/managed-switches/layer-2/dgs-3420-52t-52-port-xstack-layer-2plus-managed', NULL, 'Yes', 'webmestre@guifi.net', 2, 2, 1400535175, 1400535188),
(74, 100, 'DGS-1210-16', 'fiber|switch', NULL, 1, 16, 4, 1, NULL, 'No', NULL, NULL, NULL, '13|14|15|16', 'http://www.dlink.com/es/es/support/product/dgs-1210-series-gigabit-smart-switches', NULL, 'Yes', 'webmestre@guifi.net', 2, 2, 1400535990, 1400536014),
(75, 8, 'CCR1016-12XX', 'wireless|router|fiber', NULL, 1, 12, 4, 0, 'Yes', 'No', 'Yes', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10|ether11|ether12', NULL, '1|2|3|4', 'http://routerboard.com/CCR1016-12G', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1400967579, 1407403439),
(76, 100, 'DGS-1012-52', 'fiber|switch', NULL, 1, 52, 4, 0, NULL, 'No', NULL, '1', NULL, '49|50|51|52', 'http://www.dlink.com/es/es/business-solutions/switching/smart_switches/dgs-1210-series-gigabit-smart-plus-switches', NULL, 'Deprecated', 'webmestre@guifi.net', 1, 1, 1400969600, 1400969669),
(77, 8, 'Routerboard 2011LS', 'router|fiber', NULL, 0, 10, 1, 0, 'Yes', 'Yes', 'No', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10', NULL, 'sfp1', 'http://routerboard.com/RB2011iLS-IN', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1401384584, 1426627766),
(78, 8, 'CCR1016', 'router', NULL, 1, 12, 4, 0, 'Yes', 'No', 'Yes', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10|ether11|ether12', NULL, '1|2|3|4', 'http://routerboard.com/CCR1016-12G', NULL, 'Yes', 'webmestre@guifi.net', 2, 2, 1407673114, 1407673176),
(79, 8, 'Groove A-52HPn', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', 'wlan1', NULL, 'http://routerboard.com/RBGrooveA-52HPn', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1411074918, 1426627581),
(80, 10, 'AirFiber AF5/AF5U/AF24', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', NULL, NULL, 'http://www.ubnt.com/airfiber/airfiber5', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1411075925, 1411652914),
(81, 100, 'DIR-810L', 'wireless', NULL, 2, 5, 0, 0, 'Yes', 'Yes', 'Yes', NULL, NULL, NULL, 'http://www.dlink.com/es/es/home-solutions/connect/routers/dir-810l-wireless-ac750-dual-band-router', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1411126575, 1411126658),
(82, 10, 'PowerBeam 5AC/M2-400/M5-300/M5-400', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', 'ath0', NULL, 'http://www.ubnt.com/airmax/powerbeam/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1411651800, 1508189573),
(83, 10, 'PowerBridge M10', 'wireless', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', 'ath0', NULL, 'http://www.ubnt.com/airmax/powerbridge-m10/', NULL, 'Yes', 'webmestre@guifi.net', 163, 1, 1411652148, 1440417591),
(84, 10, 'Rocket M2/3/365/5/900/R5AC-Lite/RM2-Ti', 'wireless', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'eth0', NULL, NULL, 'http://www.ubnt.com/airmax/rocketm/', NULL, 'Yes', 'webmestre@guifi.net', 163, 1, 1411652378, 1415288168),
(85, 10, 'Rocket R5AC-Lite', 'wireless', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', NULL, NULL, 'http://www.ubnt.com/airmax/rocket-ac/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1411652531, 1411652564),
(86, 8, 'Routerboard 912UAG', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', 'wlan1', NULL, 'http://routerboard.com/RB912UAG-2HPnD', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1412873611, 1426627931),
(87, 8, 'Routerboard SXTG-5HPnD-SAr2', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', NULL, 'http://routerboard.com/RBSXTG-5HPnD-SAr2', NULL, 'Yes', 'webmestre@guifi.net', 1, 163, 1414582542, 1426627997),
(88, 8, 'Routerboard 750UP', 'router', 'Extern', 0, 5, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3|ether4|ether5', NULL, NULL, 'http://routerboard.com/RB750UP', 'Permet Firmwares de tercers', 'Yes', 'webmestre@guifi.net', 1, 1, 1414584414, 1426627911),
(89, 103, 'ARV7518PW', 'wireless|router|switch', NULL, 1, 1, 0, 0, 'No', 'Yes', 'No', 'eth0|wlan0', NULL, NULL, 'http://wiki.openwrt.org/toh/astoria/arv7518pw', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1424801243, 1424801855),
(90, 10, 'EdgeRouterLite', 'router', NULL, 0, 3, 0, 0, 'No', 'No', 'No', 'eth0|eth1|eth2', NULL, NULL, 'https://www.ubnt.com/edgemax/edgerouter-lite/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425401145, 1425403852),
(91, 10, 'EdgeRouterPOE', 'router', NULL, 0, 5, 0, 0, 'No', 'No', 'No', 'eth0|eth1|eth2|eth3|eth4', NULL, NULL, 'https://www.ubnt.com/edgemax/edgerouter-poe/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425401246, 1425403843),
(93, 10, 'EdgeSwitch24', 'fiber|switch', NULL, 1, 24, 2, 0, NULL, 'No', NULL, '0/1|0/2|0/3|0/4|0/5|0/6|0/7|0/8|0/9|0/10|0/11|0/12|0/13|0/14|0/15|0/16|0/17|0/18|0/19|0/20|0/21|0/22|0/23|0/24', NULL, '0/25|0/26', 'https://www.ubnt.com/edgemax/edgeswitch/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425490236, 1425491474),
(92, 10, 'EdgeRouter', 'router', NULL, 0, 5, 0, 0, 'No', 'No', 'No', 'eth0|eth1|eth2|eth3|eth4', NULL, NULL, 'https://www.ubnt.com/edgemax/edgerouter/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425401391, 1425403793),
(94, 10, 'EdgeSwitch48', 'fiber|switch', NULL, 1, 48, 4, 0, NULL, 'No', NULL, '0/1|0/2|0/3|0/4|0/5|0/6|0/7|0/8|0/9|0/10|0/11|0/12|0/13|0/14|0/15|0/16|0/17|0/18|0/19|0/20|0/21|0/22|0/23|0/24|0/25|0/26|0/27|0/28|0/29|0/30|0/31|0/32|0/33|0/34|0/35|0/36|0/37|0/38|0/39|0/40|0/41|0/42|0/43|0/44|0/45|0/46|0/47|0/48', NULL, '0/49|0/50|0/51|0/52', 'https://www.ubnt.com/edgemax/edgeswitch/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425491277, 1425491463),
(95, 10, 'ToughSwitch5-POE', 'switch', NULL, 1, 5, 0, 0, NULL, 'No', NULL, '0/1|0/2|0/3|0/4|0/5', NULL, NULL, 'https://www.ubnt.com/accessories/toughswitch/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425497144, 1425497165),
(96, 10, 'ToughSwitch8-PRO', 'switch', NULL, 1, 8, 0, 0, NULL, 'No', NULL, '0/1|0/2|0/3|0/4|0/5|0/6|0/7|0/8', NULL, NULL, 'https://www.ubnt.com/accessories/toughswitch/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1425497199, 1425509510),
(97, 8, 'Routerboard RB750P-PB', 'router', NULL, 1, 5, 0, 0, NULL, 'No', NULL, 'ether1|ether2|ether3|ether4|ether5', NULL, NULL, 'http://routerboard.com/RB750P-PB', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1427364537, 1427364694),
(98, 8, 'CCR1009-8G-1S-1S+PC', 'wireless|router|fiber', NULL, 1, 8, 2, 1, 'Yes', 'No', 'Yes', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|', NULL, '1', 'http://routerboard.com/CCR1009-8G-1S-1SplusPC', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1427364795, 1433178601),
(99, 8, 'Routerboard RB951Ui-2HnD', 'wireless|router|switch', NULL, 1, 5, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1|ether2|ether3|ether4|ether5', 'wlan1', NULL, 'http://routerboard.com/RB951Ui-2HnD', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1427366297, 1427366384),
(100, 8, 'Routerboard 2011UiAS-RM', 'router|fiber', NULL, 0, 10, 1, 1, 'Yes', 'No', 'Yes', 'ether1|ether2|ether3|ether4|ether5|ether6|ether7|ether8|ether9|ether10', NULL, '1|', 'http://routerboard.com/RB2011UiAS-RM', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1433178454, 1433247841),
(101, 8, 'Routerboard SXTG-5HPacD', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', NULL, 'http://routerboard.com/RBSXTG-5HPacD', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1433184234, 1433184277),
(102, 99, 'Generic x86 (qMp no WiFi)', 'router', NULL, 0, 4, 0, 0, 'No', 'No', 'No', 'eth0|eth1|eth2|eth3', NULL, NULL, 'N/A', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1448559080, 1448559206),
(103, 14, 'Apu', 'wireless|router', NULL, 2, 3, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0|eth1|eth2', 'wlan0|wlan1', NULL, 'http://www.pcengines.ch/apu1d.htm', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1448615751, 1448615816),
(104, 104, 'WT3020', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', 'wlan0', NULL, 'http://www.nexx.com.cn/index.php/home/detail?pid=199', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1450186804, 1450186841),
(105, 104, 'WT1520', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0', 'wlan0', NULL, 'http://www.nexx.com.cn/index.php/home/detail?pid=195', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1450197307, 1450197349),
(106, 105, 'R1', 'wireless|router', NULL, 1, 5, 0, 0, 'Yes', 'Yes', 'Yes', 'LAN1|LAN2|LAN3|LAN4|LAN5', 'radio0', NULL, 'http://www.bananapi.com/index.php/component/content/article?layout=edit&id=59', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1458569549, 1458569619),
(109, 10, 'AirMaxM5 LBE-M5-23, LBE-5AC-23, LBE-5AC-', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'eth0', 'ath0', NULL, 'https://dl.ubnt.com/datasheets/LiteBeam/LiteBeam_DS.pdf', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1458942059, 1458942246),
(108, 8, 'Routerboard RB850Gx2', 'router', NULL, 1, 5, 0, 0, NULL, 'No', NULL, 'ether1|ether2|ether3|ether4|ether5', NULL, NULL, 'http://routerboard.com/RB850Gx2', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1458858399, 1458858469),
(110, 8, 'Routerboard RBDynaDishG-5HacD', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'Yes', 'Yes', 'ether1', '1', NULL, 'https://routerboard.com/RBDynaDishG-5HacD', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472464964, 1472465074),
(111, 8, 'Routerboard RB922UAGS-5HPacT-NM', 'wireless|router|fiber', NULL, 1, 1, 1, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', 'sfp1', 'https://routerboard.com/RB922UAGS-5HPacT-NM', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472471428, 1472471461),
(112, 8, 'Routerboard RB922UAGS-5HPacD-NM', 'wireless|router', NULL, 1, 1, 1, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', 'sfp1', 'https://routerboard.com/RB922UAGS-5HPacD-NM', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472471531, 1472471650),
(113, 8, 'Routerboard RB921UAGS-5SHPacT-NM', 'wireless|router', NULL, 1, 1, 1, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', 'sfp1', 'https://routerboard.com/RB921UAGS-5SHPacT-NM', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472471721, 1472471775),
(114, 8, 'Routerboard RB921UAGS-5SHPacD-NM', 'wireless|router', NULL, 1, 1, 1, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', 'sfp1', 'https://routerboard.com/RB921UAGS-5SHPacD-NM', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472471835, 1472471897),
(115, 8, 'Routerboard RB921GS-5HPacD-19S', 'wireless|router|fiber', NULL, 1, 1, 1, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', 'sfp1', 'https://routerboard.com/RB921GS-5HPacD-19S', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472471978, 1472472013),
(116, 8, 'Routerboard RB921GS-5HPacD-15S', 'wireless|router|fiber', NULL, 1, 1, 1, 0, 'Yes', 'Yes', 'Yes', 'ether1', 'wlan1', 'sfp1', 'https://routerboard.com/RB921GS-5HPacD-15S', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472485606, 1472746094),
(117, 8, 'Routerboard RB911G-5HPacD-NB', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', 'wlan1', NULL, 'https://routerboard.com/RB911G-5HPacD-NB', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472485785, 1472485801),
(118, 8, 'Routerboard RBLHG-5nD', 'wireless|router', NULL, 1, 1, 0, 0, 'Yes', 'No', 'Yes', 'ether1', 'wlan1', NULL, 'https://routerboard.com/RBLHG-5nD', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1472486044, 1472486065),
(119, 8, 'RouterBoard RB3011UiAS-RM', 'router', NULL, 1, 11, 0, 1, NULL, 'No', NULL, 'ETH1|ETH2|ETH3|ETH4|ETH5|ETH6|ETH7|ETH8|ETH9|ETH10|SFP', NULL, NULL, 'https://routerboard.com/RB3011UIAS-RM', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1491492780, 1491492969),
(120, 10, 'EdgePoint R6', 'router|fiber|switch', NULL, 1, 5, 1, 0, NULL, 'No', NULL, 'eth0|eth1|eth2|eth3|eth4', NULL, 'eth5', 'https://www.ubnt.com/edgemax/edgepoint/', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1517690919, 1517691012),
(121, 106, 'APE522-II', 'wireless|router', NULL, 2, 2, 0, 0, 'Yes', 'Yes', 'Yes', 'eth0.1|eth1.2', 'wlan0|wlan1', NULL, 'http://www.zbtlink.com/products/gateway/ZBT-APE522II.html', NULL, 'Yes', 'webmestre@guifi.net', 1, 1, 1519460669, 1519460835);
");


  // --
  // -- user status types
  // --
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'user_status', 'New',  'New');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'user_status', 'Pending',  'Pending');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'user_status', 'Approved', 'Approved');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'user_status', 'Rejected', 'Rejected');");

  // --
  // -- content filter types
  // --hidden
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'filter', 'porn',  'Porn & explicit sex content');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'filter', 'violence', 'Violence & Aggressive content');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'filter', 'downloads', 'Downloads, file-sharing...');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'filter', 'drugs',  'Drugs');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'filter', 'video', 'Audio & Video sites');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('6', 'filter', 'gambling', 'Gambling');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('7', 'filter', 'hacking',  'Illegal hacking & cracking');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('8', 'filter', 'mail', 'Email & webmail sites');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('9', 'filter', 'ads', 'Advertising');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('10', 'filter', 'proxy',  'External proxys');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('11', 'filter', 'redirect', 'Redirectors');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('12', 'filter', 'spyware', 'Spyware');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('13', 'filter', 'cracks', 'Illegal warez exchange, cracks...');");

  // --
  // -- maintenance types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'maintainer'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'maintainer', 'Volunteer', 'Volunteer');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'maintainer', 'FO', 'Fibre Optics - Professional');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'maintainer', 'Wireless', 'Wireless - Professional');");

  // --
  // -- SLA types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'sla'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('1', 'sla', 'none', 'Best effort');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('2', 'sla', '8x5', '8x5: Labour times/days');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('3', 'sla', '8x7', '8x7: All days/labour times');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('4', 'sla', '24x5', '24x5: Labour days/all times');");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES ('5', 'sla', '24x7', '24x7: All days/times');");

  // --
  // -- Model Class types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'model_class'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES " .
  		"('1', 'model_class', 'wireless', 'wireless')," .
  		"('2', 'model_class', 'router', 'router')," .
  		"('3', 'model_class', 'fiber', 'fiber optics')," .
  		"('4', 'model_class', 'switch', 'switch or hub')" .
  		";");

  // --
  // -- FO port types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'fo_port'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES " .
  		"('1', 'fo_port', 'LX',  'LX 10km 1310nm SM duplex')," .
  		"('2', 'fo_port', 'EX',  'EX 40km 1310nm SM duplex')," .
  		"('3', 'fo_port', 'XD',  'XD 40km 1550nm SM duplex')," .
  		"('4', 'fo_port', 'ZX',  'ZX 80km 1550nm SM duplex')," .
  		"('5', 'fo_port', 'EZX', 'EZX 120km 1550nm SM duplex')," .
  		"('6', 'fo_port', 'BX',  'BX 10km 1550nm SM single')," .
  		"('7', 'fo_port', 'CWDM','CWDM Various Wavelengths')," .
  		"('8', 'fo_port', 'SFSW','SFSW Single Wlength to CWDM')," .
  		"('9', 'fo_port', 'SX',  'SX 850nm MM duplex')" .
  		";");

  // --
  // -- FO connection types
  // --
  update_sql("DELETE FROM `guifi_types` WHERE `type` = 'fo_conn'");
  db_query("INSERT INTO {guifi_types} (id, type, text, description) VALUES " .
  		"('1', 'fo_conn', 'fusion', 'fusion')," .
  		"('2', 'fo_conn', 'SC', 'SC connector')," .
  		"('3', 'fo_conn', 'LC', 'LC Connector')" .
  		";");

  // --
  // -- Interface class options
  // --
  update_sql("INSERT INTO {guifi_types} (id, type, text, description, relations) VALUES " .
  		"('1', 'vlan', 'vlan',    'Virtual Lan','all')," .
  		"('2', 'vlan', 'vap',     'Virtual AP','radio')," .
        "('3', 'vlan', 'wds/p2p', 'WDS PtP link','all')," .
        "('4', 'vlan', 'vrrp',    'VRRP','all')," .

        "('1', 'tunnel', 'pptp', 'PPTP','all')," .
  		"('2', 'tunnel', 'sstp', 'SSTP','all')," .
  		"('3', 'tunnel', 'sstp', 'SSTP','all')," .
        "('4', 'tunnel', 'pppoe', 'PPPoE','all')," .
        "('5', 'tunnel', 'ovpn', 'Open VPN','all')," .
        "('6', 'tunnel', 'eoip', 'EoIP','all')," .
        "('7', 'tunnel', 'ipip', 'IPIP','all')," .
        "('8', 'tunnel', 'gre', 'GRE','all')," .

  		"('1', 'aggregation', 'bridge', 'Bridge','all')," .
  		"('2', 'aggregation', '802.3ad', 'Bonding 802.3ad','all')," .
  		"('3', 'aggregation', 'abackup', 'Bonding Active Backup','all')," .
        "('4', 'aggregation', 'balb', 'Bonding Balanced Alb','all')," .
        "('5', 'aggregation', 'brr', 'Bonding Balanced RR','all')," .
        "('6', 'aggregation', 'btlb', 'Bonding Balanced TLB','all')," .
        "('7', 'aggregation', 'bxor', 'Bonding Balanced XOR','all')," .
        "('8', 'aggregation', 'bbroadcast', 'Bonding Broadcast','all'),".
        "('9', 'aggregation', 'ndual', 'NStreme Dual','radio')");

  // --
  // -- Unsolclick stuff
  // --
  update_sql("INSERT INTO `guifi_configuracioUnSolclic` (`id`, `mid`, `fid`, `enabled`, `snmp_id`, `plantilla`, `tipologia`, `notification`, `user_created`, `user_changed`, `timestamp_created`, `timestamp_changed`, `template_file`) VALUES
(1, 40, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(2, 40, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(3, 40, 18, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(4, 40, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(5, 15, 5, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(6, 15, 4, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(7, 15, 21, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(8, 15, 9, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(9, 15, 12, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(10, 15, 18, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(11, 56, 21, 0, 'ra0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(12, 39, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(13, 39, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(14, 39, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(15, 16, 5, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(16, 16, 4, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(17, 16, 21, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(18, 16, 9, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(19, 16, 12, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(20, 16, 18, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(21, 16, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(22, 16, 3, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(23, 17, 2, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(24, 17, 5, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(25, 17, 4, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(26, 17, 21, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(27, 17, 9, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(28, 17, 12, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(29, 17, 18, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(30, 17, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(31, 17, 3, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(32, 17, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(33, 16, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(34, 18, 5, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(35, 18, 4, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(36, 18, 21, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(37, 18, 9, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(38, 18, 12, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(39, 18, 18, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(40, 18, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(41, 18, 3, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(42, 18, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(43, 1, 2, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(44, 1, 5, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(45, 1, 4, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(46, 1, 21, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(47, 1, 9, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(48, 1, 12, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(49, 1, 18, 0, 'eth1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(50, 1, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(51, 1, 3, 0, '6', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(52, 1, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(53, 30, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(54, 30, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(55, 30, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(56, 19, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(57, 19, 6, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(58, 19, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(59, 19, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(60, 19, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(61, 19, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(62, 19, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(63, 21, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(64, 21, 6, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(65, 21, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(66, 21, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(67, 21, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(68, 21, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(69, 21, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(70, 20, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(71, 20, 6, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(72, 20, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(73, 20, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(74, 20, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(75, 20, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(76, 20, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(77, 22, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(78, 22, 6, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(79, 22, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(80, 22, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(81, 22, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(82, 22, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(83, 22, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(84, 23, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(85, 23, 6, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(86, 23, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(87, 23, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(88, 23, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(89, 23, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(90, 23, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(91, 24, 8, 0, 'br-lan|eth0.1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(92, 24, 6, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(93, 24, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(94, 24, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(95, 24, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(96, 24, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(97, 24, 7, 0, 'br0|eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(98, 27, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(99, 27, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(100, 27, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(101, 27, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(102, 28, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(103, 28, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(104, 28, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(105, 28, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(106, 29, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(107, 29, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(108, 29, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(109, 29, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(110, 31, 10, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(111, 31, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(112, 31, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(113, 31, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(114, 55, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(115, 54, 16, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(116, 54, 19, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(117, 52, 16, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(118, 52, 19, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(119, 44, 14, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(120, 44, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(121, 44, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(122, 53, 16, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(123, 53, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(124, 41, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(125, 41, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(126, 42, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(127, 42, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(128, 42, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(129, 43, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(130, 43, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(131, 43, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(132, 50, 17, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(133, 49, 17, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(134, 46, 15, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(135, 46, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(136, 47, 15, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(137, 47, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(138, 25, 11, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(139, 25, 20, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(140, 25, 13, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(141, 25, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(142, 25, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(143, 25, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(144, 25, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(145, 26, 11, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(146, 26, 20, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(147, 26, 13, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(148, 26, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(149, 26, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(150, 26, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(151, 26, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(152, 34, 11, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(153, 34, 20, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(154, 34, 13, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(155, 34, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(156, 34, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(157, 34, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(158, 34, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(159, 35, 11, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(160, 35, 20, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(161, 35, 13, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(162, 35, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(163, 35, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(164, 35, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(165, 35, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(166, 36, 11, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(167, 36, 20, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(168, 36, 13, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(169, 36, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(170, 36, 9, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(171, 36, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(172, 36, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(173, 37, 11, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(174, 37, 20, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(175, 37, 13, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(176, 37, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(177, 37, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(178, 37, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(179, 37, 8, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(180, 51, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(181, 51, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(182, 51, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(183, 51, 8, 0, 'br-wlanLan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(184, 38, 4, 0, 'br0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(185, 38, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(186, 38, 18, 0, 'wifi0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(187, 38, 8, 0, 'br-wlanLan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(188, 48, 15, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(189, 48, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(190, 45, 15, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(191, 45, 21, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(192, 57, 19, 1, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(193, 58, 16, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(194, 58, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(195, 59, 1, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(196, 48, 20, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(197, 48, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(198, 46, 22, 0, 'br-lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(199, 51, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(200, 38, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(201, 42, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(202, 60, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(203, 61, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(204, 3, 1, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(205, 62, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(206, 63, 22, 0, 'wlan0|br-lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(208, 65, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(209, 66, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(210, 67, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(211, 68, 22, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(213, 54, 23, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(216, 27, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(217, 52, 23, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(218, 53, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(219, 24, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(220, 69, 23, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(221, 70, 19, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(222, 70, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(223, 44, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(224, 57, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(225, 71, 16, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(226, 71, 19, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(227, 71, 23, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(228, 19, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(230, 77, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(231, 77, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(232, 75, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(233, 78, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(234, 79, 23, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(236, 81, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(237, 82, 24, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(274, 83, 24, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(239, 84, 24, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(240, 84, 15, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(241, 85, 24, 1, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(242, 80, 25, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(243, 45, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(244, 87, 16, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(245, 87, 19, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(246, 87, 23, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(249, 86, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(248, 88, 23, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(247, 88, 19, 0, 'wLan/Lan', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(251, 45, 27, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(252, 47, 27, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(253, 48, 27, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(254, 46, 27, 0, 'wlan0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(255, 47, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(256, 84, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(257, 89, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(258, 89, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(259, 91, 28, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(260, 90, 28, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(261, 92, 28, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(262, 31, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(263, 97, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(264, 97, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(265, 98, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(266, 98, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(267, 99, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(272, 101, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(269, 99, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(270, 100, 23, 1, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(271, 100, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(273, 101, 23, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(275, 83, 15, 1, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(276, 42, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(277, 42, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(282, 103, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(281, 103, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(280, 102, 22, 0, 'eth0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(283, 103, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(284, 104, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(285, 104, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(286, 104, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(287, 105, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(288, 105, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(289, 105, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(290, 41, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(291, 41, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(292, 41, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(293, 43, 27, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(294, 43, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(295, 43, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(296, 41, 18, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(297, 106, 29, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(298, 106, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(299, 108, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(300, 108, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(301, 109, 24, 0, 'ath0', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(302, 110, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(303, 110, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(304, 111, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(305, 111, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(306, 112, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(307, 112, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(308, 113, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(309, 113, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(310, 114, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(311, 114, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(312, 115, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(313, 115, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(314, 116, 19, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(315, 116, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(316, 117, 19, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(317, 117, 23, 0, 'wlan1|wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(318, 118, 19, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(319, 118, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(320, 119, 23, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(321, 120, 28, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(322, 120, 30, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(323, 120, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(324, 116, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(325, 116, 30, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(326, 121, 30, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(327, 121, 22, 0, '', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
(328, 122, 23, 0, 'wlan1', NULL, 0, 'webmestre@guifi.net', 1, 0, 0, 0, NULL);");


  update_sql("INSERT INTO {guifi_parametresConfiguracioUnsolclic} (id, pid, uscid, valor, dinamic, notification, user_created, user_changed, timestamp_created, timestamp_changed) VALUES
        (1,1,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(2,2,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(3,3,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(4,4,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(5,5,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(6,6,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(7,7,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(8,8,1,'',0,'webmestre@guifi.net',1,0,0,0),
	(9,9,19,'b',0,'webmestre@guifi.net',1,0,0,0),
	(10,10,19,'11M',0,'webmestre@guifi.net',1,0,0,0),
	(11,11,19,'6',0,'webmestre@guifi.net',1,0,0,0),
	(12,12,19,'45',0,'webmestre@guifi.net',1,0,0,0),
	(13,13,19,'2',0,'webmestre@guifi.net',1,0,0,0),
	(14,14,19,'2',0,'webmestre@guifi.net',1,0,0,0),
	(15,15,19,'disabled',0,'webmestre@guifi.net',1,0,0,0),
	(16,16,19,'11',0,'webmestre@guifi.net',1,0,0,0),
	(19,9,2,'b',0,'webmestre@guifi.net',1,0,0,0),
	(18,18,1,'Main/Internal - Vertical',0,'webmestre@guifi.net',1,0,0,0),
	(20,10,2,'11M',0,'webmestre@guifi.net',1,0,0,0),
	(21,11,2,'6',0,'webmestre@guifi.net',1,0,0,0),
	(22,12,2,'45',0,'webmestre@guifi.net',1,0,0,0),
	(23,13,2,'2',0,'webmestre@guifi.net',1,0,0,0),
	(24,14,2,'2',0,'webmestre@guifi.net',1,0,0,0),
	(25,15,2,'disabled',0,'webmestre@guifi.net',1,0,0,0),
	(26,16,2,'11',0,'webmestre@guifi.net',1,0,0,0),
	(27,18,2,'Main/Internal - Vertical',0,'webmestre@guifi.net',1,0,0,0),
	(125,22,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(124,23,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(33,1,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(34,2,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(57,4,33,'wan.gateway',1,'webmestre@guifi.net',1,0,0,0),
	(35,3,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(36,4,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(37,5,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(38,6,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(39,8,19,'locnick',1,'webmestre@guifi.net',1,0,0,0),
	(60,7,33,'devnick',1,'webmestre@guifi.net',1,0,0,0),
	(59,6,33,'secondarydns',1,'webmestre@guifi.net',1,0,0,0),
	(58,5,33,'primarydns',1,'webmestre@guifi.net',1,0,0,0),
	(44,7,19,'',1,'webmestre@guifi.net',1,0,0,0),
	(54,1,33,'wireless.1.ssid',1,'webmestre@guifi.net',1,0,0,0),
	(55,2,33,'wan.ipv4',1,'webmestre@guifi.net',1,0,0,0),
	(56,3,33,'wan.netmask',1,'webmestre@guifi.net',1,0,0,0),
	(61,8,33,'locnick',1,'webmestre@guifi.net',1,0,0,0),
	(68,24,33,'',1,'webmestre@guifi.net',1,0,0,0),
	(64,20,33,'firmware_name',1,'webmestre@guifi.net',1,0,0,0),
	(65,21,33,'locnick',1,'webmestre@guifi.net',1,0,0,0),
	(66,22,33,'devnick',1,'webmestre@guifi.net',1,0,0,0),
	(67,23,33,'locnick',1,'webmestre@guifi.net',1,0,0,0),
	(69,25,33,'28',0,'webmestre@guifi.net',1,0,0,0),
	(70,19,34,'',1,'webmestre@guifi.net',1,0,0,0),
	(71,2,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(72,5,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(73,6,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(74,7,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(75,11,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(76,1,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(77,3,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(78,4,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(79,8,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(80,9,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(81,10,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(82,12,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(83,13,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(84,14,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(85,15,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(86,16,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(87,18,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(88,19,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(89,20,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(90,21,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(91,22,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(92,23,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(93,24,35,'',1,'webmestre@guifi.net',1,0,0,0),
	(94,20,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(95,21,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(96,22,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(97,23,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(255,18,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(105,21,23,'',1,'webmestre@guifi.net',1,0,0,0),
	(104,20,23,'',1,'webmestre@guifi.net',1,0,0,0),
	(256,23,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(107,23,23,'',1,'webmestre@guifi.net',1,0,0,0),
	(108,1,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(109,1,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(110,5,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(111,5,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(112,25,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(113,25,20,'28',0,'webmestre@guifi.net',1,0,0,0),
	(114,4,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(115,4,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(116,2,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(117,2,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(118,3,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(119,3,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(120,24,23,'',0,'webmestre@guifi.net',1,0,0,0),
	(121,24,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(122,6,23,'',1,'webmestre@guifi.net',1,0,0,0),
	(123,6,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(126,21,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(127,20,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(128,5,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(129,6,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(130,4,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(131,2,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(132,3,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(133,1,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(134,24,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(135,8,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(136,27,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(137,28,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(138,29,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(139,32,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(140,9,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(141,30,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(142,31,6,'',1,'webmestre@guifi.net',1,0,0,0),
	(143,23,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(144,22,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(145,21,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(146,20,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(147,8,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(148,5,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(149,32,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(150,31,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(151,9,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(152,29,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(153,30,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(154,28,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(155,6,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(156,4,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(157,2,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(158,3,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(159,27,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(160,24,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(161,2,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(162,5,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(163,6,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(164,7,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(165,11,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(166,1,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(167,3,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(168,4,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(169,8,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(170,9,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(171,10,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(172,12,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(173,13,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(174,14,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(175,15,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(176,16,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(177,18,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(178,19,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(179,20,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(180,21,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(181,22,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(182,23,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(183,24,29,'',1,'webmestre@guifi.net',1,0,0,0),
	(282,4,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(281,28,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(280,30,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(279,29,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(278,9,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(277,31,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(276,32,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(275,8,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(274,24,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(273,27,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(272,6,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(271,34,25,'5ghz',0,'webmestre@guifi.net',1,0,0,0),
	(270,33,25,'2ghz-b',0,'webmestre@guifi.net',1,0,0,0),
	(269,5,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(268,20,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(267,21,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(266,7,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(265,22,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(264,36,25,'firmware_description',1,'webmestre@guifi.net',1,0,0,0),
	(263,36,6,'firmware_description',1,'webmestre@guifi.net',1,0,0,0),
	(262,35,25,'webmestre@guifi.net',0,'webmestre@guifi.net',1,0,0,0),
	(261,35,6,'webmestre@guifi.net',0,'webmestre@guifi.net',1,0,0,0),
	(260,35,24,'webmestre@guifi.net',0,'webmestre@guifi.net',1,0,0,0),
	(258,33,24,'2.4ghz-b',0,'webmestre@guifi.net',1,0,0,0),
	(232,2,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(233,5,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(234,6,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(235,7,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(236,11,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(237,1,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(238,3,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(239,4,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(240,8,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(241,9,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(242,10,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(243,12,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(244,13,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(245,14,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(246,15,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(247,16,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(248,18,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(249,19,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(250,20,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(251,21,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(252,22,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(253,23,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(254,24,30,'',1,'webmestre@guifi.net',1,0,0,0),
	(259,34,24,'5ghz',0,'webmestre@guifi.net',1,0,0,0),
	(257,7,24,'',1,'webmestre@guifi.net',1,0,0,0),
	(283,2,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(284,3,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(285,1,25,'',1,'webmestre@guifi.net',1,0,0,0),
	(312,23,22,'aaaaa',1,'webmestre@guifi.net',1,0,0,0),
	(313,22,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(288,21,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(289,20,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(290,5,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(291,6,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(292,35,22,'webmestre@guifi.net',0,'webmestre@guifi.net',1,0,0,0),
	(293,25,22,'28',0,'webmestre@guifi.net',1,0,0,0),
	(294,4,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(295,2,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(296,3,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(297,1,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(298,27,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(299,24,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(300,23,21,'aaaaa',1,'webmestre@guifi.net',1,0,0,0),
	(301,22,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(302,21,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(303,20,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(304,5,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(305,6,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(306,25,21,'28',0,'webmestre@guifi.net',1,0,0,0),
	(307,4,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(308,2,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(309,3,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(310,1,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(311,24,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(314,39,23,'',1,'webmestre@guifi.net',1,0,0,0),
	(315,39,20,'',1,'webmestre@guifi.net',1,0,0,0),
	(316,39,22,'',1,'webmestre@guifi.net',1,0,0,0),
	(317,39,21,'',1,'webmestre@guifi.net',1,0,0,0),
	(318,36,24,'firmware_description',1,'webmestre@guifi.net',1,0,0,0);");

  // insert de firmwares
  update_sql("INSERT INTO {guifi_firmware} (id, nom, descripcio, relations, enabled, notification, user_created, user_changed, timestamp_created, timestamp_changed) VALUES 
	(1,'n/a','not available','Other',0,'webmestre@guifi.net',1,0,0,0),
	(2,'Alchemy','Alchemy from sveasoft','WRT54Gv1-4|WRT54GSv1-2',0,'webmestre@guifi.net',1,0,0,0),
	(3,'Talisman','Talisman from sveasoft','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4',0,'webmestre@guifi.net',1,0,0,0),
	(4,'DD-WRTv23','DD-WRTv23Beta2 from BrainSlayer','WRT54Gv1-4|WHR-HP-G54, WHR-G54S|WRT54GL|WRT54',1,'webmestre@guifi.net',1,0,0,0),
	(5,'DD-guifi','DD-guifi from Miquel Martos','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|WHR-',1,'webmestre@guifi.net',1,0,0,0),
	(6,'RouterOSv2.9','RouterOS 2.9 from Mikrotik','Routerboard 532|Routerboard 133C|Routerboard',0,'webmestre@guifi.net',1,0,0,0),
	(7,'whiterussian','OpenWRT-whiterussian','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|Wrap',0,'webmestre@guifi.net',1,0,0,0),
	(8,'kamikaze','OpenWRT kamikaze','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|Rout',0,'webmestre@guifi.net',1,0,0,0),
	(9,'Freifunk-BATMAN','OpenWRT-Freifunk-v1.6.16 with B.A.T.M.A.N','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|WHR-',0,'webmestre@guifi.net',1,0,0,0),
	(10,'RouterOSv3.x','RouterOS 3.x from Mikrotik','Routerboard 532|Routerboard 133C|Routerboard',0,'webmestre@guifi.net',1,0,0,0),
	(11,'AirOsv221','Ubiquti AirOs 2.2.1','NanoStation2|NanoStation5|NanoStation Loco2|N',0,'webmestre@guifi.net',1,0,0,0),
	(12,'Freifunk-OLSR','OpenWRT-Freifunk-v1.6.16 with OLSR','WRT54Gv1-4|WRT54GL|WRT54GSv1-2|WRT54GSv4|WHR-',0,'webmestre@guifi.net',1,0,0,0),
	(13,'AirOsv30','Ubiquti AirOs 3.0','NanoStation2|NanoStation5|NanoStation Loco2|N',1,'webmestre@guifi.net',1,0,0,0),
	(14,'RouterOSv4.0+','RouterOSv4.0+','Routerboard 532|Routerboard 133C|Routerboard',1,'webmestre@guifi.net',1,0,0,0),
	(15,'AirOsv52','Ubiquti AirOs 5.2','AirMaxM2 Rocket/Nano/Loco|AirMaxM5 Rocket/Nan',0,'webmestre@guifi.net',1,0,0,0),
	(16,'RouterOSv4.7+','RouterOS 4.7 and newer 4.x ','Routerboard 532|Routerboard 133C|Routerboard',1,'webmestre@guifi.net',1,0,0,0),
	(17,'GuifiStationOS1.0','GuifiStationOS v1.0 from Setup Informatica','GuifiStation2|GuifiStation5',0,'webmestre@guifi.net',1,0,0,0),
	(18,'gsffirm','Firmware de GràciaSenseFils MANET','WRT54Gv1-4|WHR-HP-G54, WHR-G54S|WRT54GL|WRT54',0,'webmestre@guifi.net',1,0,0,0),
	(19,'RouterOSv5.x','RouterOS 5.x or newer from Mikrotik','Routerboard 532|Routerboard 133C|Routerboard',1,'webmestre@guifi.net',1,0,0,0),
	(20,'AirOsv3.6+','Ubiquti AirOs 3.6+','NanoStation2|NanoStation5|NanoStation Loco2|N',0,'webmestre@guifi.net',1,0,0,0),
	(21,'DD-WRTv24preSP2','DD-WRTv24preSP2 from BrainSlayer','AirMaxM2 Bullet/PwBrg/AirGrd/NanoBr|AirMaxM5 ',1,'webmestre@guifi.net',1,0,0,0),
	(22, 'qMp', 'qMp - Quick Mesh Project', 1, 'webmestre@guifi.net', 1, 0, 0, 0, 'vlans|aggregations'),
	(23, 'RouterOSv6.x', 'RouterOS 6.x or newer from Mikrotik', 1, 'webmestre@guifi.net', 1, 0, 0, 0, 'vlans|aggregations|tunnels'),
	(24, 'AirOSv7.x+', 'Ubiquiti AirOS v7.x', 1, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
	(25, 'AirFiberOs v2.x+', 'Ubiquiti AirFiberOs v2.x+', 1, 'webmestre@guifi.net', 1, 0, 0, 0, NULL),
	(27, 'OpenWrt_14.07', 'OpenWRT 14.07 Barrier Breaker', 1, 'webmestre@guifi.net', 1, 0, 0, 0, 'vlans|aggregations|tunnels'),
	(28, 'EdgeOS_v1.6', 'EdgeOS firmware v1.6\r\n', 1, 'webmestre@guifi.net', 1, 0, 0, 0, 'vlans|aggregations|tunnels'),
	(29, 'OpenWrt_15.05', 'OpenWRT 15.05 Chaos Calmer\r\n', 1, 'webmestre@guifi.net', 1, 0, 0, 0, 'vlans|aggregations|tunnels'),
	(30, 'LEDE 17.01', 'LEDE 17.01\r\n', 1, 'webmestre@guifi.net', 1, 0, 0, 0, 'vlans|aggregations|tunnels');");

}

?>
